### ISSUE TITLE
Validating client certificates with DFP

### ISSUE THREAD

**Issue by bsimpson53** [vfarcic/docker-flow-proxy#235] opened 2017-05-10 15:58 UTC
Hi,

I'm trying to use DFP to validate client side certificates. Ideally I want to be able to:

* pass a ca-file and verify parameters as bind options to give me something like:
  `bind *:443 ssl crt /run/secrets/cert ca-file /run/secrets/ca-file verify optional`
* identify services that require a verified user with a label like:
  `- com.df.verifyClientSsl=true`
* reject connections that don't have valid client certificate either by blocking them outright in the backend or redirecting them in the frontend

I'm not very familiar with haproxy, I wonder if there is a clean way to do this with multiple bind lines, serviceDomain and `verify required` instead

**Comment by vfarcic** [comment] 2017-05-10 19:09
If I understood correctly, `verifyClientSsl` should be true by default. If it's set to `false`, it should add `verify optional` to `bind`. Since certificates are global, `verifyClientSsl` should probably be proxy environment variable `VERIFY_CLIENT_SSL`. On top of that, there should be another env. var. with the address where requests will be forwarded in case of an invalid cert. Did I get it right?

**Comment by bsimpson53** [comment] 2017-05-11 13:29
I'm not sure :)

* I can't see where DFP has support for adding the `ca-file` option to the bind line, the ca-file is responsible for validating client certificates. (I've added it and the `verify` option by hacking my haproxy.tmpl)
* The default option for `verify` on the bind line is `none`
  * to block all services to users without a valid client certificate over port 443 you could use `verify required`
  * to block on a service by service basis you would need `verify optional` to be set and where verifyClientSsl is set on the service you would block requests to it where ssl_fc and !ssl_fc_has_crt 

So:

* If VERIFY_CLIENT_SSL is set as `true` on an environment variable on DFP then `verify required` would be set on the bind line. default would be `false`. Requests, I think, are rejected with a 403
* If VERIFY_CLIENT_SSL or com.df.verifyClientSsl is set as `true` on a service then `verify optional` would be set on the bind line. default would be `false`. Requests could be blocked with a 403

It seems to me that:

* it would be very unwise to use these options without closing port 80 or setting httpsOnly on the relevant services
* maybe verifyClientCert would be a better name than verifyClientSsl

More informative errors would be nice (IIS uses 403.xx errors) is it possible to surface more information in the 403 error page, and then allow people to override those through /errorfiles?

**Comment by bsimpson53** [comment] 2017-05-13 19:16
I have a working config where I've replace the frontend line in `haproxy.tmpl` with
```
frontend services{{.DefaultBinds}} ca-file /run/secrets/ca-file verify optional
```

... my backend section looks like this:
```
backend my_service-be8000
    mode http
    acl valid_c_cert_my_service8000 ssl_c_used ssl_c_verify 0
    http-request deny unless valid_c_cert_my_service8000 
    server my_service my_service:8000
```

... using a backend template like this
```
{{range .ServiceDest}}backend {{$.ServiceName}}-be{{.Port}}
    mode {{.ReqMode}}
    acl valid_c_cert_{{$.ServiceName}}{{.Port}} ssl_c_used ssl_c_verify 0
    http-request deny unless valid_c_cert_{{$.ServiceName}}{{.Port}}
    server {{$.ServiceName}} {{$.ServiceName}}:{{.Port}}{{"\n"}}{{end}}
```

**Comment by vfarcic** [comment] 2017-05-13 19:42
This is brilliant. Having the desired config makes the changes very easy. I think a new release should be available tomorrow.

**Comment by vfarcic** [comment] 2017-05-14 00:22
Here's the current plan. There will be a new global environment variable `CA_FILE` if set, it'll add `ca-file` to the SSL bindings (e.g .`443`). The will also be a new request param `verifyClientSsl`. If set to true, it'll add `acl ... ssl_c_used ssl_c_verify 0` and `http-request deny...` lines to the backend related to that service.

I'm half way through the changes but need to make a pause and finish it tomorrow. In the meantime, please let me know if you notice any problem with that (simple) plan.

**Comment by bsimpson53** [comment] 2017-05-14 16:37
Don't forget the `verify optional` on the bind line as well, if it's left as the implied default `verify none` it won't ask for the certificate from the browser.

You could also add a CA_VERIFY environment variable to control whether you get `verify none|optional|required`

**Comment by vfarcic** [comment] 2017-05-14 22:44
I was thinking of adding `verify optional` whenever there is a `CA_FILE`. Later on (or now if you have a use case for it), it can be extended to support `verifyCerts=none|optional|required`. I'm trying to add more params only when someone needs them and, in that way, keep everything as simple as possible (even though it's not simple anymore). What do you think?

[Release 1.379](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.379) contains the `CA_VERIFY` env. var. and `verifyClientSsl` param.

**Comment by vfarcic** [comment] 2017-05-14 22:44
Can you please try it out and let me know whether it works as expected?

**Comment by bsimpson53** [comment] 2017-05-15 15:14
@vfarcic that works great, thank you! :)

Re: the verify bit, the main use case I see is someone using a swarm to host a bunch of company wide services where access to any service requires a client key. It's not something I need at the moment though.

**Comment by vfarcic** [comment] 2017-05-15 22:14
I'll close this issue since the main feature is now working and deal with the verify bit separately if someone needs it.

**Closed by vfarcic** 2017-05-15 22:14 UTC

**Comment by samgurtman** [comment] 2017-06-20 00:30
Sorry to necro this, but what is the expected behaviour regarding setting verifyClientSsl=false and then passing header %[ssl_c_verify]? It is always 0 even if a client certificate is not provided. Shouldn't it be different depending on if a certificate is provided?

**Comment by vfarcic** [comment] 2017-06-21 10:10
The lines that are added to the backend are:

```
    acl valid_client_cert_myService ssl_c_used ssl_c_verify 0
    http-request deny unless valid_client_cert_myService
```

`valid_client_cert_myService` is true when SSL needs to be used (`ssl_c_used`) and verification of the SSL needs to return 0 (no error). In the second line, request is denied unless `valid_client_cert_myService` is `true`.

I might have made a mistake in those lines. What do you think @samgurtman ?
