### ISSUE TITLE
proxy no longer moving traffic thru two ports

### ISSUE THREAD

**Issue by michaelwilde** [vfarcic/docker-flow-proxy#159] opened 2017-03-02 05:07 UTC
Not sure why this is happening (and it did work at one point in time). 
I have a docker image that needs to have ports 80 and 8000 answer behind the dns name www.3clicks1beer.com

here's the yml file i'm using to launch DFP
https://gist.github.com/michaelwilde/02e01fbe68f1ea1eda4a6929f5d9561b

here's the service create command (nothing has changed about it): https://gist.github.com/michaelwilde/5f09526a10523e2cde8287ad7f77ad91

when i run this, it will answer on http://www.3clicks1beer.com (80).  It won't show a server available on http://www.3clicks1beer.com:8000 . 
here's proof we're running on port 8000 for splunk.   
https://gist.github.com/michaelwilde/47263268618bbeca74bbcffd8c2c8b0c

here's stdout logs from the proxy container when (After removing) i've added two services in... "3clicks1beer" and "deployer"
https://gist.github.com/michaelwilde/898c991cfb23675e5a5e770c6bfb8306

I'm at a point where i'm lost and my users are down.

**Comment by michaelwilde** [comment] 2017-03-02 06:41
update:  I reverted back to version 1.153, 1.154, 1.156, 1.189 (all of those versions of DFP behave as expected.   It seems at 1.198 ("Secrets Support"), i'm seeing failure to proxy the second port, or something other than thru port 80.  Port 8000 will listen and indicate "no server available"

Same behavior on 1.198 1.205 all the way up to "latest".  It could be a bug?  Happy i am at a working state though by reverting.

here is a detailed video illustrating the experience
https://www.youtube.com/watch?v=OeWcZHYVZDI

**Comment by vfarcic** [comment] 2017-03-02 11:14
Can you post proxy configs of both the working and non-working versions? Seeing diffs between the two is probably the fastest way to figure out the cause of the problem.

**Comment by michaelwilde** [comment] 2017-03-02 22:25
1.195 - https://gist.github.com/michaelwilde/ddc7b3bb9ff8141cbbfbdf0aca9fc5ea
1.189 - https://gist.github.com/michaelwilde/cae354c63b630a829df89d909b091a17

one thing im noticing in the 1.195+  the backend configs add this second line.

backend 3clicks1beer-be8080
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server 3clicks1beer 3clicks1beer:8080

vs 

1.189
backend 3clicks1beer-be8080                                                                                                                                                                                      
    mode http                                                                                                                                                                                                    
    server 3clicks1beer 3clicks1beer:8080

**Comment by michaelwilde** [comment] 2017-03-02 22:25
1.195 - https://gist.github.com/michaelwilde/ddc7b3bb9ff8141cbbfbdf0aca9fc5ea
1.189 - https://gist.github.com/michaelwilde/cae354c63b630a829df89d909b091a17

one thing im noticing in the 1.195+  the backend configs add this second line.

backend 3clicks1beer-be8080
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server 3clicks1beer 3clicks1beer:8080

vs 

1.189
backend 3clicks1beer-be8080                                                                                                                                                                                      
    mode http                                                                                                                                                                                                    
    server 3clicks1beer 3clicks1beer:8080

**Comment by michaelwilde** [comment] 2017-03-02 22:25
1.195 - https://gist.github.com/michaelwilde/ddc7b3bb9ff8141cbbfbdf0aca9fc5ea
1.189 - https://gist.github.com/michaelwilde/cae354c63b630a829df89d909b091a17

one thing im noticing in the 1.195+  the backend configs add this second line.

backend 3clicks1beer-be8080
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server 3clicks1beer 3clicks1beer:8080

vs 

1.189
backend 3clicks1beer-be8080                                                                                                                                                                                      
    mode http                                                                                                                                                                                                    
    server 3clicks1beer 3clicks1beer:8080

**Comment by vfarcic** [comment] 2017-03-02 23:20
Fixed in the release [1.228](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.228). Can you please try it out?

**Comment by michaelwilde** [comment] 2017-03-02 23:54
i'm seeing it still not work.

**Comment by vfarcic** [comment] 2017-03-03 00:09
Are the configs now the same?

**Comment by michaelwilde** [comment] 2017-03-03 00:18
seem to be the same
1.228 - https://gist.github.com/michaelwilde/9249aa9a192efb630c0b1040e8c6c337

re-open the case.  i've moved back to 1.189

**Comment by vfarcic** [comment] 2017-03-03 11:47
When I remove all the services from the configs and leave only 3clicks1beer.com, the only difference is that 1.228 uses `hdr` while 1.189 uses `hdr_dom` for domain. I changed to `hdr` because it's less strict than `hdr_dom` and I'm not sure how could it cause `3clicks1beer.com` not to load. On the other hand, that's the only difference so the culprit must be `hdr` or there's something I missed.

Is there a public image of `3clicks1beer.com` I could use to try it out?

P.S. Normally you'd specify a domain without `www.`.

**Comment by michaelwilde** [comment] 2017-03-03 17:31
normally one would specify a root domain without the www, but its also not uncommon to proxy a service by subdomain as well.  (I didnt' want it to be www.. the "users" did).

The weird thing is that www.3clicks1beer.com would load.. on port 80, but on 8000 it just 503s..

I could probably just let you in to my UCP..

**Comment by vfarcic** [comment] 2017-03-03 22:49
That would be great. When would it suit you the best?

**Comment by michaelwilde** [comment] 2017-03-06 16:49
Looks like we're good now.  1.230 is working well.  The trick is to add
-com.df.serviceDomainMatchAll=true

**Closed** 2017-03-06 16:49 UTC
