### ISSUE TITLE
Ways to improve HA of DFP

### ISSUE THREAD

**Issue by Vad1mo** [vfarcic/docker-flow-proxy#437] opened 2018-02-22 20:48 UTC
We are running DFP on 3 nodes in a 6 node cluster.  Right now we have about 20-30 services running. The 30 days avg. service availability is ~90% 

This is has various reasons. One is DFP, DFSL, LetsEncrypt (not the only). Most prominently we see **503** errors even if the service behind DFP is fine. #221

We have noticed a few patterns that cause problems.

1. For example or CI server is rescheduled on a new node, this causes a service disruption. Because our Jenkins isn't in a HA setup it should cause only a disruption of 30-60 seconds, however it often 
takes 15 minutes and more to recover. But more often the service is screwed up and 1/3 of the DFPs responds with 503. Then the only solution is to redeploy DFP.

2. If DFP is restarted it doesn't get a state and serves 1/3 of the traffic with 503

I think it would help if DFP health checks would be smarter, the main process could be started with the --check parameter and do extensive checks. 

1. Verify DFP has a state not older then 1 minute
2. The Targets are reachable (hard or soft mode) 

https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/

Its difficult to pinpoint the problem to a particular problem or but in the code, however I opened this issue to gather feedback and provide more evidence. We really would like to got productive with DFP,Swarm but since months we don't have the confidence to do this step.

**Comment by vfarcic** [comment] 2018-02-22 21:10
I can imagine two likely causes of that issue.

1. Not all DFP replicas have the same config. This can be easily checked by comparing `/cfg/haproxy.cfg` of all the containers.
2. There's something wrong with Overlay network.

Can you check point 1? From there on we can plan the next step.

> The Targets are reachable (hard or soft mode)

DFP is checking whether targets are reachable. If they're not, it pauses and retries, unless a sufficient number of attempts failed.

**Comment by mhabegger** [comment] 2018-02-22 22:08
We've seen a very similar behavior with a similar setup. (AWS, 3x t2.small Managers, 3x t2.medium workers, Ubuntu Servers, docker-ce 17.12.9)
We were not able to pinpoint the issue either, except that when removing the overlay network and recreating it, the issue would solve itself.
We've reworked our deployment to use AWS Linux instead of Ubuntu, and have not seen the issue for 3 weeks. Fingers crossed, but we still don't know exactly what the reason is.

**Comment by Vad1mo** [comment] 2018-02-22 22:21
hmm, we had also a few problems with ubuntu, and had to change a few settings, now Ubuntu looks good. However thank you for the info about the OS. We will try another OS

**Comment by thomasjpfan** [comment] 2018-02-26 19:52
While trying to get the integration tests setup on my local machine (one node), sometimes instances of DFP are still running as a container even tho the service is not running. `docker service ls` returns no services, but `docker container ls` shows the proxy is still running. When I try to `docker container rm` the DFP container, it stalls. When trying to start a new DFP service in this environment, the service will try to distribute to the stalled container, which doesn't return a STATUS OK response. This causes the new DFP service to never fully initialize. 

The only way to clean up the stalled containers is to restart the docker daemon. I believe there is a bug in the way DFP is handling processes.

**Comment by Vad1mo** [comment] 2018-02-26 23:52
One again after the weekend first new service fails to start. 503 after restarting DFSL its working. 

@jonlatorre single replica isn't an options for as because of HA and the limited allowed traffic per node. Thats why we need to user all the nodes. 

Our current configs are:

```
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEBUG=true
      - SERVICE_NAME=proxy_proxy
      - SKIP_ADDRESS_VALIDATION=false
      #- RECONFIGURE_ATTEMPTS=5
      - HTTPS_ONLY=true
      # - DEFAULT_PORTS=80 accept-proxy,443 accept-proxy:ssl
      - LOGSENE_ENABLED=true
    deploy:
      mode: global
      # replicas: 1
      placement:
        constraints: [node.role == worker]
```

I'll try it with your option to see if it gets better.

**Comment by vfarcic** [comment] 2018-02-26 23:58
@Vad1mo I understand the part of running multiple replicas but I'm not sure why do you need to use all the nodes (run it as global)? This question is for my own curiosity, not related to the issue.

Do you think you can make the issue reproducible?

@thomasjpfan I haven't noticed a similar issue with containers running after a service is destroyed. I was probably lucky. Do you think you can dig into it?

**Comment by thomasjpfan** [comment] 2018-02-27 00:45
I'm looking into it. A solution maybe to add the flag, `-g`, to `tini` as stated in their [docs](https://github.com/krallin/tini#process-group-killing). `tini` by default only kills immediate child process. Adding `-g` would kill the child process group:

```
ENTRYPOINT ["/sbin/tini", "-g" ,"--"]
```

DFP spawns child processes for haproxy, and for configuration verification.

Side node: I placed this issue on this thread, since this can cause DFP to not start up properly, thus leading to the OP problem of only 1/3 of the replicas running properly. I have this this happen on running servers as well if i'm quickly iterating over different configuration options.

**Comment by Vad1mo** [comment] 2018-02-27 22:36
@vfarcic We have now only 3 worker nodes each with limited bandwidth to the internet and between each other. In front of the nodes there is an LB from the IaaS provider. For a minimal HA Setup we could run 2 replicas only but our applications receive files and the request are between 1-100mb which are limited to 100Mbps per upload stream. The connection between nodes is 1gb/s. Following situation might occur with P(a)=66%, If we have DFP rolled out on Node1(2) and a request comes in on Node-3 it will be routed to Node1(2) first where DFP is running. If the target service is now running on Node 3 or Node 2(1) then we have already 200Mbps internal traffic. It gets worse if we scale up to 5 nodes.

**Comment by vfarcic** [comment] 2018-02-27 22:48
@Vad1mo I don't think that running a service in `global` mode solves that problem. When a request enters one of the nodes, it is picked up by Ingress, and forwarded to one of the replicas of the destination service (in this case DFP). Before forwarding, Ingress performs round-robin to elect to which replica to send it.

In other words, if each node has a replica, that does not mean that it'll receive requests entering on the same node. Each replica has an equal chance to receive that request.

The same logic goes for communication from DFP to your services. It's another round of round-robin and any replica of your services might receive that request.

If running it as `global` produces a problem in DFP, it should be fixed. There's no doubt about that. However, that will not resolve your bandwidth issues.

**Comment by Vad1mo** [comment] 2018-02-27 23:51
Yes, you are right. I didn't consider this fact in all the details. After catching up the swarm networking details, I was able to run DFP in host mode bypassing the ingress mesh.

```yml
services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - hostnet
      - net
#.....
networks:
  net:
  hostnet:
    external: true
    name: host
```

It seems like https://docs.docker.com/compose/compose-file/#host-or-none and https://docs.docker.com/engine/swarm/ingress/#bypass-the-routing-mesh are doing the same thing. I now configured both options and its not complaining. In this configuration I disabled the ingress routing mesh, which is fine as there is an LB in front of DFP.  

However this does not improve my situation with the 503. I still see 503 errors.

**Comment by Vad1mo** [comment] 2018-02-28 00:19
If have set now the external LB into round robin mode and disabled sticke session. This means now that each request goes to a new DFP instance I now can fairly good reproduce this issue.

I have a freshly deployed DFP stack and Portainer(sample app for the  503 test)
all worker nodes are restarted. If I now open a Portainer page with ~30 request then on avg. on requests fails with a 503.

Here is an example:
503 is on line 13:
```
TP/1.1"
2018-02-28T00:09:47.100536837Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:47 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:46.832] services~ func_gateway-be8080_0/func_gateway 0/0/1/267/268 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:47.354130298Z proxy_proxy.0.enzpwr3dampk@worker-node-1    | 2018/02/28 00:09:47 HAPRoxy: 10.109.119.142:10485 [28/Feb/2018:00:09:41.606] services~ portainer_portainer-be9000_0/portainer_portainer 0/0/5741/5/5746 200 175 - - ---- 1/1/4/5/2 0/0 "GET /api/teams HTTP/1.1"
2018-02-28T00:09:47.683676096Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:47 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:47.610] services~ func_gateway-be8080_0/func_gateway 0/0/0/72/72 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:47.763820913Z proxy_proxy.0.enzpwr3dampk@worker-node-1    | 2018/02/28 00:09:47 HAPRoxy: 10.109.119.142:10485 [28/Feb/2018:00:09:41.497] services~ portainer_portainer-be9000_0/portainer_portainer 0/0/5850/414/6265 200 31522 - - ---- 1/1/3/4/2 0/0 "GET /api/endpoints/1/docker/tasks?filters=%7B%22service%22:%5B%22proxy_proxy%22%5D%7D HTTP/1.1"
2018-02-28T00:09:49.346312814Z proxy_proxy.0.enzpwr3dampk@worker-node-1    | 2018/02/28 00:09:49 HAPRoxy: 10.109.119.142:10485 [28/Feb/2018:00:09:41.523] services~ portainer_portainer-be9000_0/portainer_portainer 0/0/2820/15/7820 200 4358 - - ---- 1/1/2/1/1 0/0 "GET /api/endpoints/1/docker/plugins HTTP/1.1"
2018-02-28T00:09:49.575438584Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:49 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:49.549] services~ func_gateway-be8080_0/func_gateway 0/0/1/25/26 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:49.638100140Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:49 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:49.613] services~ func_gateway-be8080_0/func_gateway 0/0/1/23/24 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:50.356113692Z proxy_proxy.0.enzpwr3dampk@worker-node-1    | 2018/02/28 00:09:50 HAPRoxy: 10.109.119.142:10485 [28/Feb/2018:00:09:44.456] services~ portainer_portainer-be9000_0/portainer_portainer 0/0/5886/12/5899 200 561 - - ---- 1/1/1/2/2 0/0 "GET /ico/favicon-32x32.png HTTP/1.1"
2018-02-28T00:09:50.422034473Z proxy_proxy.0.enzpwr3dampk@worker-node-1    | 2018/02/28 00:09:50 HAPRoxy: 10.109.119.142:10485 [28/Feb/2018:00:09:50.414] services~ portainer_portainer-be9000_0/portainer_portainer 0/0/1/5/7 200 418 - - ---- 1/1/1/2/0 0/0 "GET /ico/favicon-16x16.png HTTP/1.1"
2018-02-28T00:09:51.711492330Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:51 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:51.690] services~ func_gateway-be8080_0/func_gateway 0/0/1/19/20 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:51.789889855Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:51 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:51.756] services~ func_gateway-be8080_0/func_gateway 0/0/1/31/32 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:52.342104534Z proxy_proxy.0.enzpwr3dampk@worker-node-1    | 2018/02/28 00:09:52 HAPRoxy: 10.109.119.142:10485 [28/Feb/2018:00:09:41.511] services~ portainer_portainer-be9000_0/portainer_portainer 0/8830/-1/-1/10829 503 674 - - SC-- 1/1/0/0/3 0/0 "GET /api/endpoints/1/docker/images/json?all=0 HTTP/1.1"
2018-02-28T00:09:53.645329568Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:53 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:53.599] services~ func_gateway-be8080_0/func_gateway 0/0/1/45/46 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:53.705806977Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:53 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:53.679] services~ func_gateway-be8080_0/func_gateway 0/0/0/25/25 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:55.703771772Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:55 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:55.660] services~ func_gateway-be8080_0/func_gateway 0/0/0/42/42 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"
2018-02-28T00:09:55.773198440Z proxy_proxy.0.sw4c73to1hub@worker-node-3    | 2018/02/28 00:09:55 HAPRoxy: 10.109.107.206:2136 [28/Feb/2018:00:09:55.738] services~ func_gateway-be8080_0/func_gateway 0/0/1/23/24 200 1813 - - ---- 1/1/0/1/0 0/0 "GET /system/functions HTTP/1.1"

```

**Comment by vfarcic** [comment] 2018-02-28 00:28
@Vad1mo Can you check whether the configs of DFP containers are the same (it's in `/cfg/haproxy.cfg`)?

Confusing part is that one out of 30 requests fails. If there's a problem with synchronization of HAProxy configs, 1 out of 3 requests would fail on average (or whatever is the number of replicas). Following that line of thinking, seems that the problem might be in HAProxy itself, networking (Overlay) or Portainer.

Can you enter into one of DFP containers, install `curl` or `ab` and send a bunch of requests directly to `portainer_portainer`? If everything is OK, do the same in the rest of DFP replicas.

**Comment by Vad1mo** [comment] 2018-02-28 00:56
Here is the diff: 

Node 1 is different then 2 and 3
![image](https://user-images.githubusercontent.com/1492007/36763438-391c3a4c-1c28-11e8-9b24-39a869cd3ca3.png)

will do the load tests tomorrow and try some variations on them.

**Comment by alexanderkjeldaas** [comment] 2018-02-28 19:35
Could #442 be part of the issue here?

HAProxy aggressively tries to avoid using DNS, while docker aggressively uses DNS.

Thus when HAProxy does some DNS resolution and it fails, it will assume the service is scaled to 0, it will assume the server is down for all eternity, unless explicitly told to reload/recheck.

In a docker setting, it seems like HAProxy must be configured to aggressively *check DNS very very often*, not default of *only checking when explicitly told to*.

**Comment by Vad1mo** [comment] 2018-02-28 22:04
> Can you enter into one of DFP containers, install curl or ab and send a bunch of requests directly to portainer_portainer? If everything is OK, do the same in the rest of DFP replicas.

It looks all good, However I think that you where right with your assumption. The node where portainer was running was picking at ~100%CPU and ~100%RAM after redeploying on another node things look normal again.

**Comment by vfarcic** [comment] 2018-04-18 10:54
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.

**Closed by vfarcic** 2018-04-18 10:54 UTC
