### ISSUE TITLE
Where can I get release notes?

### ISSUE THREAD

**Issue by remy-tiitre** [vfarcic/docker-flow-proxy#378] opened 2017-11-20 12:06 UTC
I have an issue with 17.11.11-56, or to me more precise the issue starts with that release. When I updated my proxy from 17.11.03-55 to 17.11.11-56 it stoped working. All later versions fail as well.

After upgrade (no other modifications was done than updating docker-flow-proxy and docker-flow-swarm-listener versions) proxy complains about invalid configuration. Switching back to 03-55 makes everything ok again.
```
2017/11/20 11:19:23 Config validation failed. Will try again...
2017/11/20 11:19:24 Config validation failed
```
Github release notes seem to be out of date.

Latest release provides the following information after 20 retries
```
out:
Configuration file is valid

err:
[WARNING] 323/114223 (81) : config : 'stats' statement ignored for frontend 'tcpFE_54663' as it requires HTTP mode.
[WARNING] 323/114223 (81) : config : 'option forwardfor' ignored for frontend 'tcpFE_54663' as it requires HTTP mode.
[WARNING] 323/114223 (81) : config : 'stats' statement ignored for backend 'bamboo_server-be54663_2' as it requires HTTP mode.
[WARNING] 323/114223 (81) : config : 'option forwardfor' ignored for backend 'bamboo_server-be54663_2' as it requires HTTP mode.

```

Which is wierd as it says that the configuration file is valid and gives warnings only. Those warnings seem to be docker-flow-proxy bugs as well.

So where could I find more information about what changed from 17.11.03-55 to 17.11.11-56

**Comment by vfarcic** [comment] 2017-11-20 20:24
Those releases were bug fixes and (wrongly) I did not record them in release notes but only in the issues that were closed. Can you create (and post) a stack that would help me reproduce the issue? If you can, I'm sure that I can come up with a fix in no time.

**Comment by remy-tiitre** [comment] 2017-11-21 08:43
I will try, proxy container configuration is quite standard, I only add 1 additional port 8154 to listen to. I believe its the service labels that might not be that usual.

**Comment by vfarcic** [comment] 2017-12-02 23:05
This problem should be fixed with the [release 17.12.02-71](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.12.02-71). Can you please try it out and let me know if it works as expected.

**Comment by remy-tiitre** [comment] 2017-12-18 13:47
Well, it doesn't seem to be fixed. Log is still spammed with diffrent warnings like:

**Comment by remy-tiitre** [comment] 2017-12-18 14:28
extracted from cfg/haproxy.cfg
```
defaults
    ...
    option  forwardfor
    ...
    stats enable

frontend tcpFE_54663
    bind *:54663
    mode tcp
    default_backend bamboo_server-be54663_2

frontend tcpFE_8154
    bind *:8154
    mode tcp
    default_backend gocd_server-be8154_2
```

**Comment by vfarcic** [comment] 2017-12-19 15:23
Now I get it. You're right. Those defaults do not apply to `tcp` protocol. I can move them to `http` frontends. Functionally, the result will be the same since HAProxy ignores them when they do not apply, but the warnings will be gone. I can deliver it during the weekend. I hope that's OK.

**Comment by vfarcic** [comment] 2017-12-23 22:53
Moving `stats enable` to frontend is a bit more risky and complicated than I thought (`option  forwardfor` is not a problem). Since those are only warnings that do not affect DFP operations, I'll put it on `low-priority`.

**Comment by vfarcic** [comment] 2017-12-23 22:53
The fix would be to move them to http frontend. I'd appreciate if someone would help by sending a PR.

**Comment by vfarcic** [comment] 2018-03-31 22:48
Closing due to inactivity.

**Closed by vfarcic** 2018-03-31 22:48 UTC
Labels: low-priority
