### ISSUE TITLE
Does not restore secret after full restart

### ISSUE THREAD

**Issue by patran** [vfarcic/docker-flow-proxy#212] opened 2017-04-22 07:15 UTC
After docker flow proxy and swarm listener (as a docker swarm mode services, 1 replica each) are restarted fully (destroyed/rm'ed, then started again), the proxy configuration does not pick up the previously granted secret.

This may be an intractable problem, depending on how docker deals with the granting part.

**Comment by vfarcic** [comment] 2017-04-22 16:10
There are a few ways to tell DFP about the existence of a secret. Can you post the commands that would help me reproduce the problem?

**Comment by patran** [comment] 2017-04-22 21:11
I used "docker service update --secret-add" to grant the proxy access to the secret

1. Start proxy with its own overlay proxy_network
2.  docker service update --secret-add to grant the proxy the secret
3. Start service A
4. Access service A. Everything works
5. docker stack/service rm proxy
6. docker stack ps and docker service ls to ensure proxy is gone
7. proxy_network remains
8. Start proxy again
9. Check configuration with docker container exec -it $containerId cat /cfg/haproxy.cfg
10. There are no references to the secret on the "bind *:443" line

frontend services
    bind *:80
    bind *:443
    mode http

**Comment by vfarcic** [comment] 2017-04-24 13:07
@patran How are you doing the point 8? The service needs to be created with the secrets. If they're not included, the config will not have them. If a secret is not inside a service, proxy cannot invent it (it would not be much of a secret, wouldn't it?).

I would recommend creating a stack file that would, among other things, have the secret defined.

I'm not sure if I explained it well. Please let me know if I didn't and I'll do my best to be more descriptive. Can you please join http://slack.devops20toolkit.com/? We can have a chat there.

**Comment by vfarcic** [comment] 2017-05-06 14:37
@patran Is this issue resolved through my comments? Can we close this issue? If not, can you please clarify point 8 of your steps?

**Comment by vfarcic** [comment] 2017-05-20 21:16
Closing the issue due to inactivity. Please post a comment if you'd like me to reopen the issue.

**Closed by vfarcic** 2017-05-20 21:16 UTC
