### ISSUE TITLE
Multiple process inside docker-flow-proxy container cause http 503 error

### ISSUE THREAD

**Issue by dantonini** [vfarcic/docker-flow-proxy#444] opened 2018-03-09 15:21 UTC
I'm using:
- vfarcic/docker-flow-proxy:18.03.04-115
- vfarcic/docker-flow-swarm-listener:18.03.03-33

on a 5 node swarm cluster with docker engine 17.12.1-ce

I experienced http error 503 when try to reach a service. 
After some investigation I found the root of the problem: multiple haproxy processes in the same running docker-flow-proxy container.

I had to kill the container to fix the wrong behaviour. 

I tried to reproduce the problem, removing stack and redeploy it, but without success.

[docker-info.txt](https://github.com/vfarcic/docker-flow-proxy/files/1797334/docker-info.txt)

**Comment by dantonini** [comment] 2018-03-09 18:59
I faced this issue again:

Once I login into the container I see this output

/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /sbin/tini -g -- docker-flow-proxy server
    7 root       0:01 docker-flow-proxy server
10110 root       0:00 sh
11482 root       0:00 haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -s
11503 root       0:00 haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -s
11512 root       0:00 haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -s
12306 root       0:00 haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -s
12926 root       0:00 ps

/ # cat /var/run/haproxy.pid
12306

I'm using docker-flow-proxy with 2 replicas and both had the same wrong behaviour.

All I did was some docker stack deploy / rm, but again I not have a sequence to reproduce the issue :(

**Comment by vfarcic** [comment] 2018-03-11 16:13
I could not replicate this issue. New `haproxy` processes are spawned after reloads but in all cases the old ones were removed. On top of that, I have DRP in production and I just checked the processes inside its containers and in all replicas there's only one haproxy. I'm not sure how to proceed without being able to reproduce the issue.

Can you post your DFP stack or anything else you think might be useful in debugging? Maybe you're using a parameter I didn't have while trying to reproduce the issue.

**Comment by dantonini** [comment] 2018-03-12 18:37
As requested,
DFP stack and applicative stack (only the docker flow related configuration).

[proxy-stack.yml.txt](https://github.com/vfarcic/docker-flow-proxy/files/1802365/proxy-stack.yml.txt)
[app-stack.yml.txt](https://github.com/vfarcic/docker-flow-proxy/files/1803247/app-stack.yml.txt)

I'm trying to replicate the issue, I'll keep you posted

**Comment by dantonini** [comment] 2018-03-13 18:32
I did some quick test.

A breif recap of docker swarm configuration:
- 5 VM on top of vmware esxi 6.0
- 3 manager

docker stacks:
- DFP
- my java stack, 4 containers with several replicas (2-4) each one

what I did:
- on master: 
  while true; do docker stack rm mystack && sleep 30 && docker stack deploy .. && sleep 30
- on node on which docker flow proxy is running:
   while true; do docker exec -ti <CID> ps | grep haproxy | wc -l && sleep 30; done

This is the output:
1
1
1
1
3
3
8
10
11
Error response from daemon: Container <CID> is not running
0

Same output for the other container.

Docker swarm kill the both containers and reshedule they on other nodes. 

I think this a quite interesting result, do you agree?
Any ideas?
Are you able to replicate using your own stack?

**Comment by dantonini** [comment] 2018-03-13 22:20
Hi, I've replicated the issue also using the following stack:

version: '3'
services:
  sample:
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    deploy:
      resources:
        reservations:
          memory: 40M
        limits:
          memory: 60M
      replicas: 4
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomainMatchAll=true
        - com.df.serviceDomain=my.domain.com
        - com.df.port=8080      

networks:
  proxy:
    external: true

**Comment by dantonini** [comment] 2018-03-14 13:15
Today I did further tests, the issue seems to be related to:
docker stack rm

A loop of 2 o 3 docker stack deploy/rm is sufficient to have DFP containers with multiple process inside.

**Comment by patrickleet** [comment] 2018-03-14 18:56
@dantonini 
did you try with latest DFSL? - looks like there was a PR that was merged after the version you used in above stack that adding queuing. rapid deploy/rm could cause issues due to latency delivery REST requests. Queue should make sure they are sent in order..

**Comment by patrickleet** [comment] 2018-03-14 18:58
thanks for digging into this btw!

**Comment by dantonini** [comment] 2018-03-14 23:07
@patrickleet 
I'm glad to contribute! 

Using the latest version of DFPL improve A LOT the overall stability of the DFP containers, but nevertheless I was able to reproduce the issue again using the same stack and sequence described in previous comments.

Full DFP stack I'm using is:
- vfarcic/docker-flow-swarm-listener:18.03.13-35
- vfarcic/docker-flow-proxy:18.03.04-115

With this stack I had to wait more time (several minutes) to reproduce the issue but finally I did. 
I noticed, as vfarcic wrote, that for very short time (1 sec) a new process is spawned, then the old one was automatically removed.
I was quite confident that the issue was completely resolved because all was stable, then suddenly, I detect both DFP proxy replica with 6 process inside!

I'll continue to investigate this issue. 

I attached also the script I use to monitor the containers. You can use with:
 watch -n1 check-DFP-haproxy-process-count.sh <container_name>

[check-DFP-haproxy-process-count.sh.txt](https://github.com/vfarcic/docker-flow-proxy/files/1813423/check-DFP-haproxy-process-count.sh.txt)

**Comment by patrickleet** [comment] 2018-03-15 20:00
could we add a healthcheck, if count > 1, make it fail?

**Comment by patrickleet** [comment] 2018-03-15 20:04
maybe just modifying https://github.com/vfarcic/docker-flow-proxy/blob/master/scripts/check.sh to contain your checking logic as well would mitigate issues?

**Comment by vfarcic** [comment] 2018-03-18 14:27
During a short period there should be two haproxy processes (one terminating and the other one starting). `check.sh` would need to be a bit more "clever". Or, we can check that count <= 2. From what I understood, when processes do not die, they tend to be accumulated (>2) fast.

**Comment by dantonini** [comment] 2018-03-20 21:46
I think that check.sh should be abort the container on abnormal scenario rather than use it to "fix a bug", obviously you can use also for check this aspect but this solution is far to be the optimal imho.

I am be able to reproduce the issue quiet easily, also do you?
should I fork, update check.sh and create a pull request for this?

Please let me know

**Comment by vfarcic** [comment] 2018-03-26 00:45
Yes, please make a PR.

**Comment by thomasjpfan** [comment] 2018-03-28 05:37
My ps output looks like this:
```
haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 6187
```
where the last number is the previous haproxy PID.

I noticed your ps output for haproxy looks like: 
```
haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -s
```
Is this the complete output?

**Comment by vfarcic** [comment] 2018-03-28 12:17
Can you give us the list of DFP env. vars. you're using? Maybe you overwrote default reloading strategy...

**Comment by vfarcic** [comment] 2018-04-18 10:54
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.

**Closed by vfarcic** 2018-04-18 10:54 UTC
