### ISSUE TITLE
Configuration reload retry never happens

### ISSUE THREAD

**Issue by valeriomazzeo** [vfarcic/docker-flow-proxy#329] opened 2017-09-20 10:44 UTC
It seems that docker flow proxy doesn't try to reload the configuration in an event of failure:

```
05:01:38
2017/09/20 05:01:38 Starting HAProxy

05:01:38
2017/09/20 05:01:38 Starting "Docker Flow: Proxy"

05:01:43
2017/09/20 05:01:43 Got configuration from http://swarm-listener:8080.

05:01:43
2017/09/20 05:01:43 Creating configuration for the service myproject_visualizer

05:01:43
2017/09/20 05:01:43 Creating configuration for the service myproject_sync-gateway

05:01:43
2017/09/20 05:01:43 Creating configuration for the service myproject_myservice

05:01:43
2017/09/20 05:01:43 Creating configuration for the service myproject_mongo-express

05:01:43
2017/09/20 05:01:43 Creating configuration for the service myproject_myservice-legacy

05:01:43
2017/09/20 05:01:43 Reloading the proxy

05:01:54
2017/09/20 05:01:54 Command -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 11

05:01:54
[ALERT] 262/050153 (23) : parsing [/cfg/haproxy.cfg:94] : 'server myproject_myservice' : could not resolve address 'myproject_myservice'.

05:01:54
[ALERT] 262/050153 (23) : Failed to initialize server(s) addr.
```

After this, every request returns 503 service unavailable.
No further logs are available in swarm listener.
Restarting the service, cause the configuration to reload and everything works again.

**Comment by vfarcic** [comment] 2017-09-20 10:49
Can you post the stack with those services?

**Comment by valeriomazzeo** [comment] 2017-09-20 10:54
I can't post the stack, but configuration is standard:
```
  proxy:
    image: vfarcic/docker-flow-proxy:17.09.14-15
    ports:
      - "443:80"
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      labels:
        com.docker.aws.lb.arn: "aaaa111"
      placement:
        constraints: [node.role == worker]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:17.07.28-1
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  myservice:
    image: myproject/myservice
    deploy:
      labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.servicePath: "/myservice"
        com.df.port: "8080"
        com.df.reqPathSearch: "/myservice"
        com.df.addReqHeader: "Forwarded proto=https;\\ host=%[req.hdr(Host)];\\ port=443;\\ path=/myservice"
      placement:
        constraints: [node.role == worker]
```

I think `parsing [/cfg/haproxy.cfg:94] : 'server myproject_myservice' : could not resolve address 'myproject_myservice'.` is because the service was still in the process of starting.

**Comment by vfarcic** [comment] 2017-09-20 12:51
I think that the problem is with the `addReqHeader` label. Can you remove it and let me know whether the problem still persists. If it doesn't, we can explore which part of the req. header is wrong.

**Comment by valeriomazzeo** [comment] 2017-09-20 13:15
`com.df.addReqHeader` works, in fact if I restart the proxy the configuration is loaded properly.

In which way can `com.df.addReqHeader` affect the retry mechanism?

**Comment by vfarcic** [comment] 2017-09-20 13:18
@valeriomazzeo I'm not yet sure. I did not yet have time to investigate it. I just did a very quick test with two stacks (one with and one without `addReqHeader`). The first one failed and the second worked. I'll go through it in more detail later.

**Comment by valeriomazzeo** [comment] 2017-09-20 13:35
When you say:
>The first one failed and the second worked

Do you mean that it failed to retry or that it failed to load?

**Comment by vfarcic** [comment] 2017-09-20 13:37
@valeriomazzeo Please ignore my comment about the `addReqHeader` label. I messed up the stack I used for testing. The label is OK.

I'm failing to reproduce the problem. I replaced myservice with `vfarcic/go-demo` and `mongo` and it worked. Then I removed Mongo knowing that `go-demo` will never start. DFP threw the same error as the one you reported but, after that, it continued retrying. The logs are:

```
proxy_proxy.1.yuooeewpp8hv@moby    | [ALERT] 262/133129 (168) : parsing [/cfg/haproxy.cfg:60] : 'server proxy_myservice' : could not resolve address 'proxy_myservice'.
proxy_proxy.1.yuooeewpp8hv@moby    | [ALERT] 262/133129 (168) : Failed to initialize server(s) addr.
proxy_proxy.1.yuooeewpp8hv@moby    | 2017/09/20 13:31:30 Command -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 157
proxy_proxy.1.yuooeewpp8hv@moby    |
proxy_proxy.1.yuooeewpp8hv@moby    | [ALERT] 262/133129 (168) : parsing [/cfg/haproxy.cfg:60] : 'server proxy_myservice' : could not resolve address 'proxy_myservice'.
proxy_proxy.1.yuooeewpp8hv@moby    | [ALERT] 262/133129 (168) : Failed to initialize server(s) addr.
proxy_proxy.1.yuooeewpp8hv@moby    | 2017/09/20 13:31:30 Removing proxy_myservice configuration
proxy_proxy.1.yuooeewpp8hv@moby    | 2017/09/20 13:31:30 Removing the proxy_myservice configuration files
...
```

The key is in the last two lines the indicate that the service that could not be reached (`proxy_myservice`) was removed from the config. It is a relativelly new addition (a few months old) that makes sure that the rest of the services are reachable. Those entries are repeated in a loop.

I'm a bit confused why, in your case, DFP does not remove the offending service and why it does not try again. I cannot reproduce the problem myself

Is there any other information that might help me reproduce it?

**Comment by valeriomazzeo** [comment] 2017-09-20 14:54
It happens all the time to me when I update the stack.

I change the tags on my docker-compose file, then:

`docker deploy --with-registry-auth --compose-file docker-compose.yml mystack`

This results, most of the time in:
```
Updating service mystack_swarm-listener (id: aaa)
Updating service mystack_proxy (id: aaa)
Updating service mystack_myservice (id: aaa)
```

Even if only the myservice tag has been updated.

If I update the df-proxy image this way, meanwhile everything was perfectly running, the proxy always fail to reload the config and never retries.

If for some reason the above command, updates only myservice, sometimes it works, sometimes it doesn't.

**Comment by vfarcic** [comment] 2017-09-20 18:09
Seems that DFP is failing only when a service (e.g. `myservice`) and the proxy are updated at the same time. In that scenario, it retries for 10 seconds and gives up. If during that time the service is not available, it gives up. I think that no one detected it before because the proxy normally lives in a stack separate from other services and is never updated at the same time. When a service has a different lifecycle from the proxy, the information gets there from requests sent by the swarm-listener and the attempts have bigger pause and are bigger in number.

All in all, I changed the default value to 20 attempts (one second each). It can be changed with the environment variable `RECONFIGURE_ATTEMPTS`. Can you please update DFP to the latest release (`17.09.20-16`). If it fails again, please change `RECONFIGURE_ATTEMPTS` to a bigger value (e.g. `60`).

Please let me know if that fixed the problem. If it did, we'll look for a more elegant solution.

**Comment by valeriomazzeo** [comment] 2017-09-20 18:25
great, will give it a go soon

**Comment by valeriomazzeo** [comment] 2017-09-20 18:34
it works:

```
18:31:13
2017/09/20 18:31:13 Starting HAProxy
18:31:13
2017/09/20 18:31:13 Starting "Docker Flow: Proxy"
18:31:18
2017/09/20 18:31:18 Got configuration from http://swarm-listener:8080.
18:31:18
2017/09/20 18:31:18 Creating configuration for the service 1
18:31:18
2017/09/20 18:31:18 Creating configuration for the service 2
18:31:18
2017/09/20 18:31:18 Creating configuration for the service 3
18:31:18
2017/09/20 18:31:18 Creating configuration for the service 4
18:31:18
2017/09/20 18:31:18 Creating configuration for the service 5
18:31:18
2017/09/20 18:31:18 Reloading the proxy
18:31:19
2017/09/20 18:31:19 Proxy config could not be reloaded. Will try again...
18:31:20
2017/09/20 18:31:20 Proxy config could not be reloaded. Will try again...
18:31:21
2017/09/20 18:31:21 Proxy config could not be reloaded. Will try again...
18:31:22
2017/09/20 18:31:22 Proxy config could not be reloaded. Will try again...
18:31:23
2017/09/20 18:31:23 Proxy config could not be reloaded. Will try again...
18:31:24
2017/09/20 18:31:24 Proxy config could not be reloaded. Will try again...
18:31:28
2017/09/20 18:31:28 Proxy config could not be reloaded. Will try again...
18:31:32
2017/09/20 18:31:32 Proxy config could not be reloaded. Will try again...
18:31:36
2017/09/20 18:31:36 Proxy config could not be reloaded. Will try again...
18:31:38
2017/09/20 18:31:38 Proxy config could not be reloaded. Will try again...
18:31:39
2017/09/20 18:31:39 Proxy config could not be reloaded. Will try again...
18:31:41
2017/09/20 18:31:41 Proxy config could not be reloaded. Will try again...
18:31:43
2017/09/20 18:31:43 Proxy config could not be reloaded. Will try again...
18:31:44
2017/09/20 18:31:44 Proxy config was reloaded
```

Although, the time could vary, what would you propose as more final solution?

**Comment by vfarcic** [comment] 2017-09-23 10:06
I could not come up with a better solution but to change `RECONFIGURE_ATTEMPTS` to a bigger value (already implemented). It cannot be infinite since in some cases a service will never become available.

I'll close this issue. Feel free to reopen it if you come up with a suggestion how to improve this feature.

**Closed by vfarcic** 2017-09-23 10:06 UTC

**Comment by valeriomazzeo** [comment] 2017-09-23 12:06
couldn't the configuration fail to load only for the service that is unavailable?

**Comment by vfarcic** [comment] 2017-09-25 17:39
If reconfiguration with a new or updated service fails, DFP will remove that service from the config. The process repeats in a loop until timeout just in case the service is not yet available. Please let me know if you're experiencing a different behavior or if you have a better suggestion how to handle that scenario.

**Comment by sean9999** [comment] 2017-09-26 01:52
do we pass `RECONFIGURE_ATTEMPTS` to proxy or swarm-listener?
