### ISSUE TITLE
Allow whitelist in DFP to leverage x-forwarded-for

### ISSUE THREAD

**Issue by beenanner** [vfarcic/docker-flow-proxy#377] opened 2017-11-20 03:29 UTC
I believe this is a feature request, but might still be blocked by upstream docker. The idea is to allow docker-flow-proxy to allow a whitelist of IPs at the HAProxy level via x-forwarded-for. Though I'm not sure if we can accomplish this with the way Docker swarm currently works. 

Example using Google Cloud Platform since Google LBs can't implement IP restrictions yet:

GCP LB --> Docker Swarm(DFP) --> Docker Swarm(Nginx) --> (Docker Swarm(Application)

One work around currently would be to have a proxy sitting between the Google LB and the Docker Swarm to provide the whitelisting, but that isn't ideal since now we are looking at 3 LBs in front of everything. 

GCP LB --> Nginx or HAProxy --> Docker Swarm(DFP) --> Docker Swarm(Nginx) --> (Docker Swarm(Application)

Ideally using the x-forwarded-for we could inspect the original IP of the client and create a whitelist to allow certain IPs through say for 3rd party approved testing only via their IPs. The issue is that the ingress of docker swarm response currently with the 10.255.x.x address as the client IP so we need to identify the true client IP via another method. Another feature is the [proxy protocol support](http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). 

Here are a few related issues I've found both in the projects as well as upstream in docker.
[Moby #25526](https://github.com/moby/moby/issues/25526)
[DFP #348](https://github.com/vfarcic/docker-flow-proxy/issues/348)

**Comment by vfarcic** [comment] 2017-12-02 23:10
I don't think that's possible due to the way Overlay network is designed. The moment a request enters Overlay network, the original IP is lost. That means that you have to either a) not use Overlay or b) put something before it. I don't think I see a way to add this feature to DFP unless we move it outside Overlay/Ingress network.

**Comment by vfarcic** [comment] 2017-12-23 21:07
Closing since there does not seem to be a good solution that can be applied in DFP. The problem is with ingress network.

**Closed by vfarcic** 2017-12-23 21:07 UTC
