### ISSUE TITLE
Redirect from domain

### ISSUE THREAD

**Issue by aleskinen** [vfarcic/docker-flow-proxy#373] opened 2017-11-16 08:47 UTC
If I use redirectFromDomain with latest docker-flow-proxy i get errors:
core_proxy.1.n48qx5zzo2nu@dca.tek.fi    | 2017/11/15 14:46:46 Validating configuration
core_proxy.1.n48qx5zzo2nu@dca.tek.fi    | [WARNING] 318/144646 (3787) : parsing [/cfg/haproxy.cfg:58] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
core_proxy.1.n48qx5zzo2nu@dca.tek.fi    | [WARNING] 318/144646 (3787) : parsing [/cfg/haproxy.cfg:59] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.

At first it seemd to work, but now I have had several problems with domains including redirects. When I downgraded to version 17.11.01-52 they seem to work.

**Comment by vfarcic** [comment] 2017-11-17 20:29
I tried it a few moments ago. I used the labels that follow.

```
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/demo
        - com.df.redirectFromDomain=acme.com
        - com.df.serviceDomain=google.com
        - com.df.port=8080
```

Then I executed:

```bash
docker network create -d overlay proxy

docker stack deploy -c stack.yml proxy

curl -i -H "Host: acme.com" "http://localhost/demo/hello"
```

The output was:

```
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: http://google.com/demo/hello
```

There were no warnings in logs.


My best guess is that the problem occurs only with a specific combination of labels. Can you please send me the stack you're using? That should help me reproduce the issue.

**Comment by aleskinen** [comment] 2017-11-20 08:33
# Drupal to be used with external MySQL container
#
version: '3.3'

services:
  web:
    image: tukoke
    networks:
      - proxy
      - mariadb
    volumes:
      - type: volume
        source: tukoke-webroot
        target: /var/www/html/web/sites/
    environment:
      WEBROOT: /var/www/html/web
      ERRORS: 1
      RUN_SCRIPTS: 1

    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=tukoke.tek.fi
        - com.df.port=8002
        - com.df.redirectFromDomain=www.tukoke.fi,tukoke.fi
        - com.df.httpsOnly=true
      placement:
        constraints: [node.hostname == dca.tek.fi]

networks:
  proxy:
    external: true
  mariadb:
    external: true

volumes:
  tukoke-webroot:
    external: true

**Comment by vfarcic** [comment] 2017-11-21 08:36
I'm having trouble to reproduce the issue. I tried with the https://github.com/vfarcic/docker-flow-proxy/blob/master/issues/373/stack.yml stack but it did not produce the same warning. Can you help me out and try to reproduce it with `vfarcic/go-demo` or any other publicly accessible service? If I could get to the same state as you are, I'm sure it should be trivial to fix it.

**Comment by andrh** [comment] 2017-11-22 16:54
I'm experiencing a similar situation, only with `redirectWhenHttpProto`. All my services have these labels:

```
     labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${MY_DOMAIN:-mydomain.local}
        - com.df.servicePath=${SERVICE_PATH:-/myservice}
        - com.df.port=8080
        - com.df.redirectWhenHttpProto=${ENABLE_HTTPS_REDIRECT:- true}
        - com.df.httpsRedirectCode=301
```

**Comment by vfarcic** [comment] 2017-11-22 19:06
@andrh I don't have an easy way to test `redirectWhenHttpProto` manually on a real cluster so I have to rely on unit tests for this feature. I made a change that I hope should fix the problem with `redirectWhenHttpProto`. Can you please try it out with `vfarcic/docker-flow-proxy:17.11.22-65` and let me know if it works. If it doesn't, please send me the output from logs.

**Comment by andrh** [comment] 2017-11-23 08:44
Same problem. I also tried it with 17.11.01-52 and that works as expected.

```
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:40 Removing mydomain_kommentar-editor-backend configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:40 Removing the mydomain_kommentar-editor-backend configuration files
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:40 Reloading the proxy
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:40 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:40 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:41 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:41 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:42 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:42 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:43 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:43 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:44 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:44 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:45 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:45 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:46 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:46 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:47 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:47 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:48 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:48 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:49 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:49 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:50 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:50 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:51 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:51 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:52 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:52 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:53 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:53 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:54 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:54 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:55 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:55 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:56 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:56 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:57 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:57 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:58 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:58 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:59 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:23:59 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:00 Config validation failed
proxy_proxy.1.ookcztjzlnp0@moby    | out:
proxy_proxy.1.ookcztjzlnp0@moby    | Configuration file is valid
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | err:
proxy_proxy.1.ookcztjzlnp0@moby    | [WARNING] 326/082359 (1189) : parsing [/cfg/haproxy.cfg:57] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
proxy_proxy.1.ookcztjzlnp0@moby    | [WARNING] 326/082359 (1189) : parsing [/cfg/haproxy.cfg:59] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | global
proxy_proxy.1.ookcztjzlnp0@moby    |     pidfile /var/run/haproxy.pid
proxy_proxy.1.ookcztjzlnp0@moby    |     tune.ssl.default-dh-param 2048
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     # disable sslv3, prefer modern ciphers
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-bind-options no-sslv3
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-server-options no-sslv3
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | resolvers docker
proxy_proxy.1.ookcztjzlnp0@moby    |     nameserver dns 127.0.0.11:53
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | defaults
proxy_proxy.1.ookcztjzlnp0@moby    |     mode    http
proxy_proxy.1.ookcztjzlnp0@moby    |     balance roundrobin
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     option  dontlognull
proxy_proxy.1.ookcztjzlnp0@moby    |     option  dontlog-normal
proxy_proxy.1.ookcztjzlnp0@moby    |     option  http-keep-alive
proxy_proxy.1.ookcztjzlnp0@moby    |     option  forwardfor
proxy_proxy.1.ookcztjzlnp0@moby    |     option  redispatch
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 400 /errorfiles/400.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 403 /errorfiles/403.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 405 /errorfiles/405.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 408 /errorfiles/408.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 429 /errorfiles/429.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 500 /errorfiles/500.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 502 /errorfiles/502.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 503 /errorfiles/503.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 504 /errorfiles/504.http
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     maxconn 5000
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout connect 5s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout client  20s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout server  20s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout queue   30s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout tunnel  3600s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout http-request 5s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout http-keep-alive 15s
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | frontend services
proxy_proxy.1.ookcztjzlnp0@moby    |     bind *:80
proxy_proxy.1.ookcztjzlnp0@moby    |     bind *:443
proxy_proxy.1.ookcztjzlnp0@moby    |     mode http
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     acl url_monitor_monitor9090_0 path_beg /
proxy_proxy.1.ookcztjzlnp0@moby    |     acl domain_monitor_monitor9090_0 hdr_beg(host) -i monitor.mydomain.local
proxy_proxy.1.ookcztjzlnp0@moby    |     use_backend monitor_monitor-be9090_0 if url_monitor_monitor9090_0 domain_monitor_monitor9090_0
proxy_proxy.1.ookcztjzlnp0@moby    |     acl url_z-mydomain-xml-editor3000_0 path_beg /
proxy_proxy.1.ookcztjzlnp0@moby    |     acl domain_z-mydomain-xml-editor3000_0 hdr_beg(host) -i editor.mydomain.local
proxy_proxy.1.ookcztjzlnp0@moby    |     use_backend mydomain_mydomain-xml-editor-be3000_0 if url_z-mydomain-xml-editor3000_0 domain_z-mydomain-xml-editor3000_0
proxy_proxy.1.ookcztjzlnp0@moby    |     acl is_z-mydomain-xml-editor_http hdr(X-Forwarded-Proto) http
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request redirect scheme https if is_z-mydomain-xml-editor_http url_z-mydomain-xml-editor3000_0 domain_z-mydomain-xml-editor3000_0
proxy_proxy.1.ookcztjzlnp0@moby    |     acl is_z-mydomain-xml-editor_https hdr(X-Forwarded-Proto) https
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request redirect scheme https if !is_z-mydomain-xml-editor_https url_z-mydomain-xml-editor3000_0 domain_z-mydomain-xml-editor3000_0
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | userlist monitor_monitorUsers
proxy_proxy.1.ookcztjzlnp0@moby    |     user admin password $5$vOad7nyt8$qxADsuSctxsvn5Ehqn1oi41truSXfN.LW45E//zP4aB
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | backend monitor_monitor-be9090_0
proxy_proxy.1.ookcztjzlnp0@moby    |     mode http
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request add-header X-Forwarded-Proto https if { ssl_fc }
proxy_proxy.1.ookcztjzlnp0@moby    |     server monitor_monitor monitor_monitor:9090
proxy_proxy.1.ookcztjzlnp0@moby    |     acl monitor_monitorUsersAcl http_auth(monitor_monitorUsers)
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request auth realm monitor_monitorRealm if !monitor_monitorUsersAcl
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request del-header Authorization
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | backend mydomain_mydomain-xml-editor-be3000_0
proxy_proxy.1.ookcztjzlnp0@moby    |     mode http
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request add-header X-Forwarded-Proto https if { ssl_fc }
proxy_proxy.1.ookcztjzlnp0@moby    |     server mydomain_mydomain-xml-editor mydomain_mydomain-xml-editor:3000
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:00 Config validation failed
proxy_proxy.1.ookcztjzlnp0@moby    | out:
proxy_proxy.1.ookcztjzlnp0@moby    | Configuration file is valid
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | err:
proxy_proxy.1.ookcztjzlnp0@moby    | [WARNING] 326/082359 (1189) : parsing [/cfg/haproxy.cfg:57] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
proxy_proxy.1.ookcztjzlnp0@moby    | [WARNING] 326/082359 (1189) : parsing [/cfg/haproxy.cfg:59] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | global
proxy_proxy.1.ookcztjzlnp0@moby    |     pidfile /var/run/haproxy.pid
proxy_proxy.1.ookcztjzlnp0@moby    |     tune.ssl.default-dh-param 2048
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     # disable sslv3, prefer modern ciphers
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-bind-options no-sslv3
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-server-options no-sslv3
proxy_proxy.1.ookcztjzlnp0@moby    |     ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | resolvers docker
proxy_proxy.1.ookcztjzlnp0@moby    |     nameserver dns 127.0.0.11:53
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | defaults
proxy_proxy.1.ookcztjzlnp0@moby    |     mode    http
proxy_proxy.1.ookcztjzlnp0@moby    |     balance roundrobin
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     option  dontlognull
proxy_proxy.1.ookcztjzlnp0@moby    |     option  dontlog-normal
proxy_proxy.1.ookcztjzlnp0@moby    |     option  http-keep-alive
proxy_proxy.1.ookcztjzlnp0@moby    |     option  forwardfor
proxy_proxy.1.ookcztjzlnp0@moby    |     option  redispatch
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 400 /errorfiles/400.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 403 /errorfiles/403.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 405 /errorfiles/405.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 408 /errorfiles/408.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 429 /errorfiles/429.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 500 /errorfiles/500.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 502 /errorfiles/502.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 503 /errorfiles/503.http
proxy_proxy.1.ookcztjzlnp0@moby    |     errorfile 504 /errorfiles/504.http
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     maxconn 5000
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout connect 5s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout client  20s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout server  20s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout queue   30s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout tunnel  3600s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout http-request 5s
proxy_proxy.1.ookcztjzlnp0@moby    |     timeout http-keep-alive 15s
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | frontend services
proxy_proxy.1.ookcztjzlnp0@moby    |     bind *:80
proxy_proxy.1.ookcztjzlnp0@moby    |     bind *:443
proxy_proxy.1.ookcztjzlnp0@moby    |     mode http
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    |     acl url_monitor_monitor9090_0 path_beg /
proxy_proxy.1.ookcztjzlnp0@moby    |     acl domain_monitor_monitor9090_0 hdr_beg(host) -i monitor.mydomain.local
proxy_proxy.1.ookcztjzlnp0@moby    |     use_backend monitor_monitor-be9090_0 if url_monitor_monitor9090_0 domain_monitor_monitor9090_0
proxy_proxy.1.ookcztjzlnp0@moby    |     acl url_z-mydomain-xml-editor3000_0 path_beg /
proxy_proxy.1.ookcztjzlnp0@moby    |     acl domain_z-mydomain-xml-editor3000_0 hdr_beg(host) -i editor.mydomain.local
proxy_proxy.1.ookcztjzlnp0@moby    |     use_backend mydomain_mydomain-xml-editor-be3000_0 if url_z-mydomain-xml-editor3000_0 domain_z-mydomain-xml-editor3000_0
proxy_proxy.1.ookcztjzlnp0@moby    |     acl is_z-mydomain-xml-editor_http hdr(X-Forwarded-Proto) http
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request redirect scheme https if is_z-mydomain-xml-editor_http url_z-mydomain-xml-editor3000_0 domain_z-mydomain-xml-editor3000_0
proxy_proxy.1.ookcztjzlnp0@moby    |     acl is_z-mydomain-xml-editor_https hdr(X-Forwarded-Proto) https
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request redirect scheme https if !is_z-mydomain-xml-editor_https url_z-mydomain-xml-editor3000_0 domain_z-mydomain-xml-editor3000_0
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | userlist monitor_monitorUsers
proxy_proxy.1.ookcztjzlnp0@moby    |     user admin password $5$vOad7nyt8$qxADsuSctxsvn5Ehqn1oi41truSXfN.LW45E//zP4aB
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | backend monitor_monitor-be9090_0
proxy_proxy.1.ookcztjzlnp0@moby    |     mode http
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request add-header X-Forwarded-Proto https if { ssl_fc }
proxy_proxy.1.ookcztjzlnp0@moby    |     server monitor_monitor monitor_monitor:9090
proxy_proxy.1.ookcztjzlnp0@moby    |     acl monitor_monitorUsersAcl http_auth(monitor_monitorUsers)
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request auth realm monitor_monitorRealm if !monitor_monitorUsersAcl
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request del-header Authorization
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | 
proxy_proxy.1.ookcztjzlnp0@moby    | backend mydomain_mydomain-xml-editor-be3000_0
proxy_proxy.1.ookcztjzlnp0@moby    |     mode http
proxy_proxy.1.ookcztjzlnp0@moby    |     http-request add-header X-Forwarded-Proto https if { ssl_fc }
proxy_proxy.1.ookcztjzlnp0@moby    |     server mydomain_mydomain-xml-editor mydomain_mydomain-xml-editor:3000
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:00 Creating configuration for the service mydomain_mydomain-lov-backend
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:00 Reloading the proxy
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:00 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:00 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:01 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:01 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:02 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:02 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:03 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:03 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:04 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:04 Config validation failed. Will try again...
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:05 Sending distribution request to http://10.0.0.25:8080/v1/docker-flow-proxy/reconfigure?alertAnnotations.1=summary%3DService+has+fewer+running+replicas+than+it%27s+scaled+for&alertFor.1=60s&alertIf.1=%40replicas_running&alertLabels.1=severity%3Dhigh&alertName.1=replicas_running&distribute=false&httpsRedirectCode=301&port=8080&redirectWhenHttpProto=true&replicas=1&serviceDomain=mydomain.local&serviceName=mydomain_kommentar-editor-backend&servicePath=%2Fkommentar-editor-backend
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:05 Validating configuration
proxy_proxy.1.ookcztjzlnp0@moby    | 2017/11/23 08:24:05 Config validation failed. Will try again...
```

**Comment by vfarcic** [comment] 2017-11-23 15:28
@kungfu71186 Can you work on those items?

**Comment by vfarcic** [comment] 2017-12-02 23:11
This should be fixed with [release 17.12.02-71](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.12.02-71) (thanks @kungfu71186). Can someone try it out and confirm it?

**Comment by vfarcic** [comment] 2017-12-23 21:04
I'll close this issue assuming that the [release 17.12.02-71](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.12.02-71) fixed it. Feel free to reopen if that's not the case.

**Comment by freshollie** [comment] 2018-06-29 05:19
I'm experiencing this issue on the latest image. It appears these warnings are still being considered as errors.

```
[WARNING] 179/050513 (4928) : parsing [/cfg/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 179/050513 (4929) : parsing [/cfg/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
The configuration file is valid, but there still may be a misconfiguration somewhere that will give unexpected results, please verify: 
stdout:
stderr:
[WARNING] 179/050513 (4929) : parsing [/cfg/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
2018/06/29 05:05:14 Proxy config was reloaded
2018/06/29 05:05:19 Reloading the proxy
2018/06/29 05:05:19 Validating configuration
[WARNING] 179/050519 (4940) : parsing [/cfg/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
Configuration file is valid
The configuration file is valid, but there still may be a misconfiguration somewhere that will give unexpected results, please verify: 
stdout:
Configuration file is valid
stderr:
[WARNING] 179/050519 (4940) : parsing [/cfg/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 179/050519 (4941) : parsing [/cfg/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
The configuration file is valid, but there still may be a misconfiguration somewhere that will give unexpected results, please verify: 
stdout:
stderr:
[WARNING] 179/050519 (4941) : parsing [/cfg/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
2018/06/29 05:05:19 Proxy config was reloaded
```

My solution at the moment is to remove `redirectFromDomain` and put the redirect directly into the `EXTRA_FRONTEND` but I don't like this solution.

**Comment by freshollie** [comment] 2018-06-30 18:57
Update on this. This seems to be unrelated, and actually related to https://github.com/docker-flow/docker-flow-proxy/issues/31 with the "latest" image, which seems to be spawning haproxy processes over and over.

**Closed** 2018-07-21 09:51 UTC
