### ISSUE TITLE
Check config file before reload

### ISSUE THREAD

**Issue by kungfu71186** [vfarcic/docker-flow-proxy#331] opened 2017-09-22 20:52 UTC
Came across an issue today where I had a valid but bad config. Basically there was a cert I was loading that was good, but it didnt have the key. This made the proxy take out all configurations and continually reload the config going back and forth between the dummy config and gathering information of the services.

There was no errors in the log that showed anything out of the ordinary either.

Come to find out, it was actually an error with the config.

Is it possible to create a config before reloading, test the config, and then deploy and reload the config?

I was able to do this by

`haproxy -c -V -f /cfg/haproxy.cfg`

This will not only give an output if the config is wrong or correct, but it will give the proper exit status as well. 0 good, 1 bad.

One way to reproduce is, is to simply add a cert to the /certs directory without a key in it. It will try to load and fail.

**Comment by vfarcic** [comment] 2017-09-22 22:31
Beta version of the fix is published as `vfarcic/docker-flow-proxy:issue-331`. It passed all the automated tests but I did not have time to test it manually as well. Can you please try it out yourself and let me know whether it works as expected?

**Comment by kungfu71186** [comment] 2017-09-22 22:50
Sure. I'll let you know

**Comment by kungfu71186** [comment] 2017-09-22 23:04
@vfarcic Nice! it seems to work just fine. I have a config that is running with valid certs. I went in configured the crt-list and add the "bad" cert. Tried to reload the proxy and it fails validation. 

It outputs the current config if bad.

The only thing I don't see is the actual error from haproxy. 

But im pretty happy with this. It won't break the proxy at least if there is a bad config.

**Comment by vfarcic** [comment] 2017-09-22 23:14
That's great to hear! Jenkins job is building a new release while I'm writing this...

I'm a bit confused with *The only thing I don't see is the actual error from haproxy*. When validation fails it should output *Config validation failed* followed by the error from haproxy and the config (https://github.com/vfarcic/docker-flow-proxy/blob/issue-331/proxy/ha_proxy.go#L509). It might be the case that haproxy sends the message to stdout, not stderr. I'll check it out later and put it in one of the next releases.

**Comment by kungfu71186** [comment] 2017-09-23 00:21
@vfarcic actually might need to open this back up. Seems to not work for another case I found. 

It shows that it failed, but it reloads the config anyway after so many attempts and then crashes the proxy like before.

**Comment by vfarcic** [comment] 2017-09-23 09:29
Can you send me the steps I could use to reproduce it?

**Comment by kungfu71186** [comment] 2017-09-23 12:02
@vfarcic yes, #333 

`com.df.setReqHeader=ssl_client_cert -----BEGIN\ CERTIFICATE-----\ %[ssl_c_der,base64]\ -----END\ CERTIFICATE-----\ if { ssl_fc_has_crt }`

**Comment by vfarcic** [comment] 2017-09-25 17:36
Closed through #333. Please reopen this issue if you have a better proposal or if it does not work as expected.

**Comment by kungfu71186** [comment] 2017-09-25 18:59
@vfarcic my concern is that if you mis-configure one service, it brings down all the services because it tries to load a bad config. I'm proposing that after the reconfiguration attempts, it just falls back to the config its currently at and not load the new version. If there is a change in the services, DFL will pick up those changes, DFP will then try to reload the configurations again like normal. Starts the process all over. It shouldn't try to load a bad config though. Right now it seems like it loads the bad configuration after it the reconfiguration attempts have been reached. 

For example, if it's set to 20 times, it will try to reload 20 times and fails, but then it loads it anyway after the 20th time.

**Comment by vfarcic** [comment] 2017-09-25 19:03
@kungfu71186 Right now, each time it ads a service, it reloads the config and, if that fails, removes the service (falls back to the previous config). The problem is that I missed your comment  about loading bad config after all failed attempts. I'll look into it tonight or tomorrow.

**Comment by vfarcic** [comment] 2017-09-25 19:10
I think I found the problem. Services are removed on failed haproxy reload when a request to reconfigure is coming from DFSL directly. However, the same logic is not implemented when DFP starts (e.g. a new replica) and asks for the info from DFSL during initialization. Can that be the use case you experienced?

**Comment by kungfu71186** [comment] 2017-09-25 19:19
I don't think so, right now I'm only testing with 1 replica. I'll do some more testing though and let you know. Basically I have 1 DFL, 1 DFP, say service1, service 2.

1.  Load service 1 (assume good config)
2.  Load service 2 (assume good config)
3. Add new config to service 2 (bad config)
4. HAProxy detects change and test the config. HAproxy says its bad (does this 20 times)
5. HAProxy appears to load it anyway after this

At least that is what it appears to be doing, but i'll verify tomorrow for you and so some more testing on it.

**Comment by vfarcic** [comment] 2017-09-25 19:25
Great! I'll wait for your findings and, if you can provide a simple scenario that replicates it, create a functional test that fails and implement the change.

**Comment by kungfu71186** [comment] 2017-09-25 19:38
Sure, let me see if i can replicate with go-demo

**Comment by kungfu71186** [comment] 2017-09-25 19:55
Ok, yeah, I just tried. Maybe I was mistaken. I could have sworn it loaded after it tried to load the config x amount of attempts. But yes, it looks like it just removes the service in question instead. This should be sufficient enough. Go ahead and close, if I see the issue appear, i'll reopen with exact steps.

Thanks again!

**Comment by vfarcic** [comment] 2017-09-25 20:01
@kungfu71186 The feature that removes a service is reload fails is relatively new. You might have tried with one of the releases before the feature was added. In any case, I'm glad it works.

Closing the issue...

**Closed by vfarcic** 2017-09-25 20:01 UTC
