### ISSUE TITLE
Intermittent 404s and 503s

### ISSUE THREAD

**Issue by bengrisafi** [vfarcic/docker-flow-proxy#287] opened 2017-07-11 14:44 UTC
We have been seeing this issue for a while now in various environments while running older versions, but we were able to reproduce in a testbed after upgrading the proxy services to current release versions. 

We've seen 404s and 503s occur randomly among the services, but typically only 1 exhibits the behavior.
The haproxy config files are typically identical, but one of the containers will start throwing these errors while the other two seem to function normally. 

Scaling the service can sometime fix this, but we don't see much of any errors. App logs show 200s, but the proxy logs show 404s or 503s. 

Please let me know if I'm missing anything or have any further ideas on how to better test this or get any better info back to troubleshoot this issue.

Curl returns
``` 
HTTP/1.1 404 Not Found
Date: Tue, 11 Jul 2017 12:18:39 GMT
Connection: keep-alive
Server: Kestrel

HTTP/1.1 503 Service Unavailable
Date: Tue, 11 Jul 2017 12:18:37 GMT
Content-Type: text/html
Connection: keep-alive
Cache-Control: no-cache
```

Setup: 
Docker swarm (1.13) on AWS 
3 worker nodes
3 manager nodes
3 replicated proxy containers- docker-flow-proxy 1.419
1 swarm-listener container - docker flow-swarm-listener 1.32
4 total dotnet core services with 2 containers

Service labels:
Labels:
 com.df.distribute=true
 com.df.notify=true
 com.df.port=5000
 com.df.reqPathReplace=/
 com.df.reqPathSearch=service<number>/?
 com.df.serviceDomain=domain.net
 com.df.servicePath=service<number>

Reproducer:
curl health status ~30000-50000x
ex. curl https://domain.net/service/healthstatus -s -o /dev/null 

App Logs:
ex. 

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.9841ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://domain.net/healthstatus
```

Proxy logs:
example of a redistribution and 404/503 requests
```
2017/07/11 00:19:19 Creating configuration for the service service1
2017/07/11 00:19:19 HAPRoxy: Proxy services started.
2017/07/11 00:19:19 HAPRoxy: Proxy service1-be5000 started.
2017/07/11 00:19:19 HAPRoxy: Proxy service2-be5000 started.
2017/07/11 00:19:19 HAPRoxy: Proxy service3-be5000 started.
2017/07/11 00:19:19 HAPRoxy: Proxy service4-be5000 started.
2017/07/11 00:19:19 HAPRoxy: Stopping frontend services in 0 ms.
2017/07/11 00:19:19 HAPRoxy: Stopping backend service1-be5000 in 0 ms.
2017/07/11 00:19:19 HAPRoxy: Stopping backend service2-be5000 in 0 ms.
2017/07/11 00:19:19 HAPRoxy: Stopping backend service3-be5000 in 0 ms.
2017/07/11 00:19:19 HAPRoxy: Stopping backend service4-be5000 in 0 ms.
2017/07/11 00:19:19 HAPRoxy: Proxy services stopped (FE: 0 conns, BE: 0 conns).
2017/07/11 00:19:19 HAPRoxy: Proxy service1-be5000 stopped (FE: 0 conns, BE: 0 conns).
2017/07/11 00:19:19 HAPRoxy: Proxy service2-be5000 stopped (FE: 0 conns, BE: 0 conns).
2017/07/11 00:19:19 HAPRoxy: Proxy service3-be5000 stopped (FE: 0 conns, BE: 0 conns).
2017/07/11 00:19:19 HAPRoxy: Proxy service4-be5000 stopped (FE: 0 conns, BE: 0 conns).
2017/07/11 00:19:19 Reloading the proxy
2017/07/11 00:19:19 Proxy config was reloaded
...
2017/07/11 11:38:42 HAPRoxy: 10.255.0.13:64552 [11/Jul/2017:11:38:42.770] services service1-be5000/service1 0/0/16/38/59 200 611 - - ---- 1/1/0/1/0 0/0 "GET /service1/healthstatus HTTP/1.1"
2017/07/11 11:38:44 HAPRoxy: 10.255.0.13:64552 [11/Jul/2017:11:38:44.436] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "GET /service2/healthstatus HTTP/1.1"
2017/07/11 11:38:44 HAPRoxy: 10.255.0.13:64560 [11/Jul/2017:11:38:44.680] services service3-be5000/service3 0/0/0/16/16 200 328 - - ---- 1/1/0/1/0 0/0 "GET /service3/healthstatus HTTP/1.1"
2017/07/11 11:39:26 HAPRoxy: 10.255.0.13:64624 [11/Jul/2017:11:39:26.999] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "HEAD /service2/healthstatus HTTP/1.1"
2017/07/11 11:39:28 HAPRoxy: 10.255.0.13:64626 [11/Jul/2017:11:39:28.020] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "HEAD /service2/healthstatus HTTP/1.1"
2017/07/11 11:55:37 HAPRoxy: 10.255.0.13:40461 [11/Jul/2017:11:55:37.782] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "GET / HTTP/1.1"
2017/07/11 12:18:20 HAPRoxy: 10.255.0.13:7768 [11/Jul/2017:12:18:20.100] services service1-be5000/service1 0/0/0/1/1 200 611 - - ---- 1/1/0/1/0 0/0 "GET /service1/healthstatus HTTP/1.1"
2017/07/11 12:18:21 HAPRoxy: 10.255.0.13:7770 [11/Jul/2017:12:18:20.280] services service2-be5000/service2 0/0/0/816/839 200 448 - - ---- 2/2/0/1/0 0/0 "GET /service2/healthstatus HTTP/1.1"

```

Haproxy config file
```
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048
    log 127.0.0.1:1514 local0

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

defaults
    mode    http
    balance roundrobin

    option  http-keep-alive
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s


frontend services
    bind *:80
    bind *:443
    mode http

    option httplog
    log global
    acl url_service15000 path_beg /service1
    acl domain_service15000 hdr(host) -i domain.net
    use_backend service1-be5000 if url_service15000 domain_service15000
    acl url_service25000 path_beg /service2
    acl domain_service25000 hdr(host) -i domain.net
    use_backend service2-be5000 if url_service25000 domain_service25000
    acl url_service35000 path_beg /service3
    acl domain_service35000 hdr(host) -i domain.net
    use_backend service3-be5000 if url_service35000 domain_service35000
    acl url_service45000 path_beg /service4/
    acl domain_service45000 hdr(host) -i domain.net
    use_backend service4-be5000 if url_service45000 domain_service45000

backend service1-be5000
    mode http
    log global
    http-request set-path %[path,regsub(/service1/?,/)]
    server service1 service1:5000

backend service2-be5000
    mode http
    log global
    http-request set-path %[path,regsub(/service2/?,/)]
    server service2 service2:5000

backend service3-be5000
    mode http
    log global
    server service3 service3:5000

backend service4-be5000
    mode http
    log global
    server service4 service4:5000

```

**Comment by vfarcic** [comment] 2017-07-11 16:37
DFP does not forward requests to containers but to Docker networking which takes care of load balancing and forwarding to a specific container. You might get inconsistent results if different DFP replicas are having different configurations but, as you said, that's not the case. I think that the cause of the problem lies beyond the proxy either in networking or the services you're running.

Can you enable DFP debugging? You'd need to set the environment variable `DEBUG` to `true` (more info in http://proxy.dockerflow.com/config/#environment-variables). That will give us more information what is happening with individual requests. With debugging enabled, try to reproduce 404/503 responses and paste DFP logs.

**Comment by bengrisafi** [comment] 2017-07-11 16:43
The proxy is on the proxy network and all the services are using that docker network. 
I have debugging enabled and I have some of those calls in the Proxy logs in my original post. 

```
2017/07/11 11:38:42 HAPRoxy: 10.255.0.13:64552 [11/Jul/2017:11:38:42.770] services service1-be5000/service1 0/0/16/38/59 200 611 - - ---- 1/1/0/1/0 0/0 "GET /service1/healthstatus HTTP/1.1"
2017/07/11 11:38:44 HAPRoxy: 10.255.0.13:64552 [11/Jul/2017:11:38:44.436] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "GET /service2/healthstatus HTTP/1.1"
2017/07/11 11:38:44 HAPRoxy: 10.255.0.13:64560 [11/Jul/2017:11:38:44.680] services service3-be5000/service3 0/0/0/16/16 200 328 - - ---- 1/1/0/1/0 0/0 "GET /service3/healthstatus HTTP/1.1"
2017/07/11 11:39:26 HAPRoxy: 10.255.0.13:64624 [11/Jul/2017:11:39:26.999] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "HEAD /service2/healthstatus HTTP/1.1"
2017/07/11 11:39:28 HAPRoxy: 10.255.0.13:64626 [11/Jul/2017:11:39:28.020] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "HEAD /service2/healthstatus HTTP/1.1"
2017/07/11 11:55:37 HAPRoxy: 10.255.0.13:40461 [11/Jul/2017:11:55:37.782] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 0/0/0/0/0 0/0 "GET / HTTP/1.1"
2017/07/11 12:18:20 HAPRoxy: 10.255.0.13:7768 [11/Jul/2017:12:18:20.100] services service1-be5000/service1 0/0/0/1/1 200 611 - - ---- 1/1/0/1/0 0/0 "GET /service1/healthstatus HTTP/1.1"
2017/07/11 12:18:21 HAPRoxy: 10.255.0.13:7770 [11/Jul/2017:12:18:20.280] services service2-be5000/service2 0/0/0/816/839 200 448 - - ---- 2/2/0/1/0 0/0 "GET /service2/healthstatus HTTP/1.1"

```

**Comment by vfarcic** [comment] 2017-07-11 16:58
Seems like it could not find the path for those with 503. You can see that from `services/<NOSRV>`. Can you confirm that all requests are going through the domain `domain.net`? Can you (temporarily) remove the domain and confirm that the same result is happening?

**Comment by bengrisafi** [comment] 2017-07-12 18:49
All our my tests were using that domain. I've removed the service domain label and reran the curl commands specifying the ip address and saw the same.

**Comment by vfarcic** [comment] 2017-07-13 15:59
First of all, sorry for my previous comment. I just noticed that you did include debug information in the initial post and there was no need for me to ask for it again.

There is a problem with communication between the proxy and your backend services. You can see that from `SC--`. All the requests that ended with `503` have `SC--`. That field represents "the condition the session was in when the session ended".

From HAProxy docs:

"SC The [back-end] server or an equipment between it and haproxy explicitly refused the TCP connection (the proxy received a TCP RST or an ICMP message in return). Under some circumstances, it can also be the network stack telling the proxy that the server is unreachable (eg: no route, or no ARP response on local network). When this happens in HTTP mode, the status code is likely a 502 or 503 here."

I'm not sure what exactly is causing that but it is either related to internal networking on your service "behaving badly" and terminating incoming connections.

I wish I could tell you more but HAProxy does not point to exact problems outside it own domain. It only knows what happens to the connection it sends to the backend service and, in this case, it was refused by one of the backends.

**Comment by narcoticfresh** [comment] 2017-07-14 06:55
@bengrisafi 
i'm observing exactly the same behavior on my current project. in my case it's an nginx - if accessed directly via port, i get no errors - accessing via DFP i get occasional and irregular failures..

my log also shows similar:

```
2017/07/14 06:33:49 HAPRoxy: 10.255.0.2:44524 [14/Jul/2017:06:33:31.119] tcpFE_443 test_nginx-be443/test_nginx 1/0/18385 85156 -- 0/0/0/0/0 0/0
2017/07/14 06:33:49 HAPRoxy: 10.255.0.2:44548 [14/Jul/2017:06:33:49.711] tcpFE_443 tcpFE_443/<NOSRV> -1/-1/0 0 SC 1/1/0/0/0 0/0
2017/07/14 06:33:49 HAPRoxy: 10.255.0.2:44550 [14/Jul/2017:06:33:49.721] tcpFE_443 tcpFE_443/<NOSRV> -1/-1/0 0 SC 1/1/0/0/0 0/0
2017/07/14 06:33:56 HAPRoxy: 10.255.0.2:44554 [14/Jul/2017:06:33:56.481] tcpFE_443 tcpFE_443/<NOSRV> -1/-1/0 0 SC 1/1/0/0/0 0/0
2017/07/14 06:33:56 HAPRoxy: 10.255.0.2:44556 [14/Jul/2017:06:33:56.482] tcpFE_443 test_nginx-be443/test_nginx 1/0/465 1031 -- 2/2/2/2/0 0/0
2017/07/14 06:33:57 HAPRoxy: 10.255.0.2:44558 [14/Jul/2017:06:33:56.947] tcpFE_443 test_nginx-be443/test_nginx 1/0/324 1031 -- 2/2/1/1/0 0/0
2017/07/14 06:33:57 HAPRoxy: 10.255.0.2:44560 [14/Jul/2017:06:33:57.271] tcpFE_443 test_nginx-be443/test_nginx 1/0/340 1031 -- 2/2/1/1/0 0/0
2017/07/14 06:33:57 HAPRoxy: 10.255.0.2:44562 [14/Jul/2017:06:33:57.611] tcpFE_443 test_nginx-be443/test_nginx 1/1/328 1031 -- 1/1/1/1/0 0/0
2017/07/14 06:33:58 HAPRoxy: 10.255.0.2:44564 [14/Jul/2017:06:33:57.941] tcpFE_443 test_nginx-be443/test_nginx 1/0/354 1031 -- 2/2/2/2/0 0/0
2017/07/14 06:33:58 HAPRoxy: 10.255.0.2:44566 [14/Jul/2017:06:33:58.295] tcpFE_443 test_nginx-be443/test_nginx 1/0/268 1031 -- 2/2/2/2/0 0/0
2017/07/14 06:33:58 HAPRoxy: 10.255.0.2:44568 [14/Jul/2017:06:33:58.563] tcpFE_443 test_nginx-be443/test_nginx 1/0/322 1031 -- 2/2/1/1/0 0/0
2017/07/14 06:33:59 HAPRoxy: 10.255.0.2:44574 [14/Jul/2017:06:33:58.885] tcpFE_443 test_nginx-be443/test_nginx 1/0/368 1031 -- 1/1/1/1/0 0/0
2017/07/14 06:33:59 HAPRoxy: 10.255.0.2:44576 [14/Jul/2017:06:33:59.254] tcpFE_443 tcpFE_443/<NOSRV> -1/-1/0 0 SC 1/1/0/0/0 0/0
2017/07/14 06:33:59 HAPRoxy: 10.255.0.2:44578 [14/Jul/2017:06:33:59.604] tcpFE_443 tcpFE_443/<NOSRV> -1/-1/0 0 SC 1/1/0/0/0 0/0
```
@vfarcic 
the problem is not DFP per se, it's of course haproxy doing something wrong.

my gut feeling is that it's the dns resolution that is done. as we normally would give haproxy a list of ip's to balance, dns resolution is not an issue. obviously in the context of DFP, it's exactly the point to **not** give ip addresses ;-)

i'll try to fiddle with some dns related settings or maybe to give an isolated test case.

**Comment by narcoticfresh** [comment] 2017-07-14 07:46
@vfarcic @bengrisafi 
i had no success fiddling around with dns settings and the timeouts seem to be fine already (speaking about haproxy conf)

## Testcase

I created a very primitive testcase and I could verify the problem there as well.

### My environment

This test case was done using a local swarm cluster using docker-machine. Nothing fancy.. 

Env (node0 is the manager):
```
user@host:~/git/something$ docker-machine ssh node0 docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
````

### Stuff to reproduce

I created this gist containing all necessary to reproduce:
https://gist.github.com/narcoticfresh/ec2ff31ae2c96bd5160f95de85141c35

It has:
* [file-stack-proxy-test-yml](https://gist.github.com/narcoticfresh/ec2ff31ae2c96bd5160f95de85141c35#file-stack-proxy-test-yml) - the compose file. proxy + a simple nginx as workload. i deliberately bound this to another port as this matches my use case more.
* [file-test-req-sh](https://gist.github.com/narcoticfresh/ec2ff31ae2c96bd5160f95de85141c35#file-test-req-sh) - a simple bash script that sends 200 requests to that service (please change the ip address there)
* [my log](https://gist.github.com/narcoticfresh/ec2ff31ae2c96bd5160f95de85141c35#file-my-log-after-executing-it-partial-showing-some-errors) - my log after running the bash script. please see the existence of `NOSRV` lines there (search with `CTRL+F`)

@vfarcic could you try to run this locally to see if you can reproduce the same behavior?

**Comment by vfarcic** [comment] 2017-07-14 18:21
The example you posted indeed reproduces the issue. However, it is happening only with `com.df.reqMode=tcp`. As soon as I remove that label and re-deploy the stack, it works like a charm. Now I'm not sure whether the problem is in:

a) HAProxy TCP configuration (I could not find anything "strange")

b) with nginx when accepting TCP requests

c) it gets confused when cUrl sends an HTTP request and the proxy forwards it to TCP

In any case, the problem is not reproducible when using HTTP all the way. Can you confirm that nginx service works well with TCP?

**Comment by narcoticfresh** [comment] 2017-07-16 11:22
@vfarcic first, yes, I can confirm the problem seems not to exist in `regMode=http`..

Let's not forget that technically, `http` is _also_ `tcp` based.

We just define how haproxy should talk with the `backend server` - either HTTP (OSI level 7 as i remember(?)); or on layer 4 (i guess) using TCP.. But at the end of the day, this is _all_ TCP anyway ;-)

So yes, of course nginx works with TCP. A browser requesting a website is also opening a TCP connection to then talk HTTP over that connection.

My problem is now that I'm not sure how we can analyze what is really happening. For me also the haproxy configuration looks OK (as I'm *not* having two frontends binding on the same port, that could lead to erratic behavior).

We must somehow find out how we can analyze that this is either (my guesses)
* a haproxy issue in the context we use it(?)
* a docker networking issue dropping packets(?)

Any ideas how we can find out where the problem is? Can we packet sniff in a swarm? (didn't find any infos on that)

**Comment by vfarcic** [comment] 2017-07-18 21:08
I guess that the best course of action would be to publish the port of the service and test it by sending TCP requests to it. If it works, the problem is probably not in Docker networking but in HAProxy config. @narcoticfresh, do you think you'd have time to try it out?

**Comment by narcoticfresh** [comment] 2017-07-20 09:13
@vfarcic & @bengrisafi 
sooo... i wasted time again and fiddled around a bit... this issue is really strange and oddly annoying..
but i think i have news, even if i don't know it it helps anything..

**bottom line**: I really don't think it's a docker networking issue anymore.. and there is a workaround, but i think it's not usable..

## my new test script
so i extended my test script a bit, i'm now counting the times i see the 'welcome to nginx' in the responses.. we always fire 200 requests.. so if we see it 200 times, we are fine..

```bash
#!/usr/bin/env bash

rm log

for i in {1..200}
do
 curl -H 'Host: test.local' http://<manager ip>:88 >> log
 echo "---------------------------" >> log
done

echo "number of times of nginx welcome page: "
grep 'Welcome to nginx!' log | grep h1 | wc -l
```

And the same using netcat (this is the TCP test you asked for):

```bash
#!/usr/bin/env bash

rm log

for i in {1..200}
do
 echo GET / | netcat <manager-ip> 8888 >> log
 echo "---------------------------" >> log
done

echo "number of times of nginx welcome page: "
grep 'Welcome to nginx!' log | grep h1 | wc -l
```

## testing direct access

### host networking

so, i directly exposed our nginx service on the *host*, like so:

```yml
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 8888
        protocol: tcp
        mode: host
```
note the `mode: host`, that according to moby/moby#34161 this completely circumvents ingress/swarm networking..

so let's run our *netcat* test script (pure tcp tool):

```
user@host:~$ bash test-req-netcat.sh 
number of times of nginx welcome page: 
200
```
OK: 100% success rate

### back to ingress

so now i redeploy the stack, **not** using host mode anymore:

```yml
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 8888
        protocol: tcp
        mode: ingress
```
run it again:
```
user@host:~$ bash test-req-netcat.sh 
number of times of nginx welcome page: 
200
```
OK: 100% success rate

My take away: Doesn't seem like a networking issue..

## next step: back to haproxy

So i ended up setting the `haproxy.cfg` file as a read-only volume to the `docker-flow-proxy` container so I could freely fiddle around with the haproxy config..

So i tried many different `option` directives, changing the way the `acl` is done, added `tcp-request inspect-delay 5s` to frontend - it all didn't help..

### the situation as in this issue

When i run the test script (the curl based), i get:

```
curl: (52) Empty reply from server
number of times of nginx welcome page: 
99
```
or
```
curl: (52) Empty reply from server
number of times of nginx welcome page: 
121
```
or
```
number of times of nginx welcome page: 
107
```
**IMPORTANT NOTE**
@vfarcic it seems that always "around half" of my requests fail.. it somehow looks "roundrobbin"ish - could it be haproxy tries to balance when there is nothing to balance?

i tried to fiddle with the `balance` option, but to no use..

### the workaround - it solves it and not

Having seen that, I tried to specify the frontend like this:

```
frontend tcpFE_88                                                                     
    bind *:88                                                                         
    mode tcp                                                                          
    option tcplog                                                                     
    log global                                                                        
                                                               
    default_backend proxy_nginx-be80                                                 
                                                                                      
    acl domain_proxy_nginx80 hdr(host) -i test.local                                 
    use_backend proxy_nginx-be80 if domain_proxy_nginx80
```

Please note the added `default_backend` line.

Let's test again:

```
number of times of nginx welcome page: 
200
```
OK: 100% success rate

I ran it multiple times, it is always 100%..
I also increased the test script to 1000 requests, and also there:

```
100   612  100   612    0     0   368k      0 --:--:-- --:--:-- --:--:--  597k
number of times of nginx welcome page: 
1000
```

## Conclusion

Sorry for getting so long, but it needs to be shown ;-)

### Why the workaround is no good

So this workaround is fine.. but we cannot use it i guess - we don't know a "default backend" as every frontend has multiple.. And if every frontend only can have 1 (the default) backend, the purpose of docker-flow-proxy is not fulfilled..

### Further

IMHO, now we are left with to options, both concerning haproxy:
* haproxy tries to balance stuff where there is nothing to balance - that's why around 50% of requests fail..
* There is somehow a problem with the `hdr(host)` lookup in about half the cases. I tried to change that to `hdr_dom(host)`, that didn't make a difference. But as I've seen in SSL context, also `req.ssl_sni` has the same problem.

Any ideas?

**Comment by narcoticfresh** [comment] 2017-07-20 09:33
@vfarcic 
i think somehow this is related to #168 we use `hdr_dom`/`hdr` in tcp mode - but it's just strange it works in about half the requests(?)

**Comment by vfarcic** [comment] 2017-07-21 12:23
@narcoticfresh That is, indeed, strange. TCP (unless you use SNI) cannot be forwarded based on domain. There are no headers HAProxy could use to deduce the domain of a request. So, the question is not why it does not work (it shouldn't) but how come it works sometimes.

**Comment by carl-utter** [comment] 2017-09-08 22:28
We are not using NGINX but rather Ubuntu for our Swarm Cluster Instances... but we ran into this same problem. We believe it was because we had our DF Proxy configured with "CONNECTION_MODE:-http-keep-alive" because our Portainer Service required it in order to function correctly.

_DF Proxy Stack File Example (environment section)_
```
environment:
  - LISTENER_ADDRESS=swarm-listener
  - MODE=swarm
  - CONNECTION_MODE=${CONNECTION_MODE:-http-keep-alive}
  - TIMEOUT_HTTP_REQUEST=15
  - TIMEOUT_CONNECT=15
```

However, that connection wasn't friendly for our other various services (which include an emalgum of Node, Express, Swagger API, Mongo, Mongoose, ReactJS, etc...)

**Solution:**
Once we discovered that we could pass in the "http-keep-alive" as a "service label" to scope the connection mode at the service level we were then able to change our DF Proxy Stack file to set the connection mode to be "http-server-close", thusly:

_Updated DF Proxy Stack File Example (environment section):_
```
environment:
  - LISTENER_ADDRESS=swarm-listener
  - MODE=swarm
  - CONNECTION_MODE=${CONNECTION_MODE:-http-server-close}
  - TIMEOUT_HTTP_REQUEST=15
  - TIMEOUT_CONNECT=15
```

Then, in our Portainer Stack file we added to the labels section:

_Portainer Stack File Example (labels section):_
```
labels:
  - com.df.notify=true
  - com.df.distribute=true
  - com.df.connectionMode=http-keep-alive
  - com.df.servicePath=/portainer
  - com.df.reqPathSearch=/portainer
  - com.df.port=9000
```

Taking these steps resolved this specific issue for us and in the future if we have any other services that require the "http-keep-alive" connection mode we will do the same thing for them too.

**Comment by vfarcic** [comment] 2017-10-07 11:00
Closing the issue since @carl-utter answered/solved the problem and no one reported an issue after his comments. Feel free to reopen if the issue still persists.

**Closed by vfarcic** 2017-10-07 11:00 UTC

**Comment by miko** [comment] 2018-03-22 12:07
FYI - I had exactly the same problem/solution as @carl-utter, I suggest adding this info to the FAQ - that would help me spare few hours of googling.

**Comment by vfarcic** [comment] 2018-03-22 12:10
@miko Can you do us a favor and submit a PR with the changes to the docs?
