### ISSUE TITLE
shutting down all services...

### ISSUE THREAD

**Issue by AshleyAitken** [vfarcic/docker-flow-proxy#284] opened 2017-07-08 08:17 UTC
I am sorry, I am not sure the best place to ask this question.  I am using Docker Flow (thanks so much) and had it working but now I am having problems.  

For some reason all the haproxy services are started and then stopped (see below).

I have turned on debug mode and previously saw an issue that one of the servers could not be found.  However, that error message is no longer seen.  

Flow Listener keeps on trying to send through configuration, and Proxy seems to start them but I guess either haproxy or Proxy is stopping them.  

2017-07-08T07:38:52.566695138Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Proxy config was reloaded
2017-07-08T07:38:52.566883685Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Creating configuration for the service development_grade-web_nodejs
2017-07-08T07:38:52.715471697Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Reloading the proxy
2017-07-08T07:38:52.718970527Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy services started.
2017-07-08T07:38:52.718998174Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_academy-web_nodejs-be3000 started.
2017-07-08T07:38:52.719003502Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_api_rest_gateway-be80 started.
2017-07-08T07:38:52.719007136Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_assess-web_nodejs-be3000 started.
2017-07-08T07:38:52.719010917Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_award-web_nodejs-be3000 started.
2017-07-08T07:38:52.719014337Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_grade-web_nodejs-be3000 started.
2017-07-08T07:38:52.719063404Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_ms_nodejs-be3002 started.
2017-07-08T07:38:52.719070491Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_pc-web_nodejs-be3000 started.
2017-07-08T07:38:52.719073849Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_qual-web_nodejs-be3000 started.
2017-07-08T07:38:52.719078267Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping frontend services in 0 ms.
2017-07-08T07:38:52.719083606Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_academy-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.719089444Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_api_rest_gateway-be80 in 0 ms.
2017-07-08T07:38:52.719094849Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_assess-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.719100462Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_award-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.719134071Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_grade-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.719145179Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_ms_nodejs-be3002 in 0 ms.
2017-07-08T07:38:52.719151131Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_pc-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.719157012Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_qual-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.719171484Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy services stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719176319Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_academy-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719179719Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_api_rest_gateway-be80 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719184921Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_assess-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719190507Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_award-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719239204Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_grade-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719244296Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_ms_nodejs-be3002 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719247589Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_pc-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719251979Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_qual-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.719257289Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Proxy config was reloaded

I am using latest versions of Docker Flow Proxy and Swarm-Listener.  It was working a few days ago,  and I have made changes to my system config so it may not be Docker Flow.  

Thanks for any tips.

Cheers, Ashley.

**Comment by AshleyAitken** [comment] 2017-07-08 08:19
I should also mention that I can't even run the health check ping on Flow Proxy
http://...:8080/v1/docker-flow-proxy/ping
It times out.  It did return config JSON previously.

**Comment by AshleyAitken** [comment] 2017-07-08 08:21
Here is the start of the Docker Flow Proxy log:
2017-07-08T07:38:44.291455524Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:44 Starting HAProxy
2017-07-08T07:38:44.431984272Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:44 Starting "Docker Flow: Proxy"
2017-07-08T07:38:49.437480582Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Got configuration from http://listener:8080.
2017-07-08T07:38:49.437930368Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_award-web_nodejs
2017-07-08T07:38:49.440699952Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_pc-web_nodejs
2017-07-08T07:38:49.442917475Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_qual-web_nodejs
2017-07-08T07:38:49.445338459Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_academy-web_nodejs
2017-07-08T07:38:49.447753638Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_api_rest_gateway
2017-07-08T07:38:49.450417954Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_assess-web_nodejs
2017-07-08T07:38:49.453323602Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_ms_nodejs
2017-07-08T07:38:49.455731056Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Creating configuration for the service development_grade-web_nodejs
2017-07-08T07:38:49.473331404Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Reloading the proxy
2017-07-08T07:38:49.481378122Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy services started.
2017-07-08T07:38:49.481405592Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_academy-web_nodejs-be3000 started.
2017-07-08T07:38:49.481410357Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_api_rest_gateway-be80 started.
2017-07-08T07:38:49.481414232Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_assess-web_nodejs-be3000 started.
2017-07-08T07:38:49.481417634Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_award-web_nodejs-be3000 started.
2017-07-08T07:38:49.481421372Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_grade-web_nodejs-be3000 started.
2017-07-08T07:38:49.481424554Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_ms_nodejs-be3002 started.
2017-07-08T07:38:49.481427710Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_pc-web_nodejs-be3000 started.
2017-07-08T07:38:49.481430964Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 HAPRoxy: Proxy development_qual-web_nodejs-be3000 started.
2017-07-08T07:38:49.482408878Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:49 Proxy config was reloaded
2017-07-08T07:38:52.153834680Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=3000&serviceName=development_pc-web_nodejs&servicePath=%2Fpc
2017-07-08T07:38:52.156175046Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=3002&serviceName=development_ms_nodejs&servicePath=%2Fmock-webapi%2Fv0
2017-07-08T07:38:52.156220311Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Creating configuration for the service development_pc-web_nodejs
2017-07-08T07:38:52.156228742Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=80&serviceName=development_api_rest_gateway&servicePath=%2Fwebapi%2Fv0
2017-07-08T07:38:52.156247734Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=3000&serviceName=development_award-web_nodejs&servicePath=%2Faward
2017-07-08T07:38:52.156254751Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=3000&serviceName=development_academy-web_nodejs&servicePath=%2Facademy
2017-07-08T07:38:52.156261744Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=3000&serviceName=development_assess-web_nodejs&servicePath=%2Fassess
2017-07-08T07:38:52.156268219Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=3000&serviceName=development_qual-web_nodejs&servicePath=%2Fqual
2017-07-08T07:38:52.158703031Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Sending distribution request to http://10.0.8.31:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=3000&serviceName=development_grade-web_nodejs&servicePath=%2Fgrade
2017-07-08T07:38:52.165602184Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Reloading the proxy
2017-07-08T07:38:52.174861006Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy services started.
2017-07-08T07:38:52.175033536Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_academy-web_nodejs-be3000 started.
2017-07-08T07:38:52.175039511Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_api_rest_gateway-be80 started.
2017-07-08T07:38:52.175043308Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_assess-web_nodejs-be3000 started.
2017-07-08T07:38:52.175046839Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_award-web_nodejs-be3000 started.
2017-07-08T07:38:52.175050276Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_grade-web_nodejs-be3000 started.
2017-07-08T07:38:52.175057001Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_ms_nodejs-be3002 started.
2017-07-08T07:38:52.175060539Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_pc-web_nodejs-be3000 started.
2017-07-08T07:38:52.175063879Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_qual-web_nodejs-be3000 started.
2017-07-08T07:38:52.175085256Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping frontend services in 0 ms.
2017-07-08T07:38:52.175089568Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_academy-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.175092989Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_api_rest_gateway-be80 in 0 ms.
2017-07-08T07:38:52.175096398Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_assess-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.175099806Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_award-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.175103134Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_grade-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.175106319Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_ms_nodejs-be3002 in 0 ms.
2017-07-08T07:38:52.175109473Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_pc-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.175120189Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Stopping backend development_qual-web_nodejs-be3000 in 0 ms.
2017-07-08T07:38:52.175123686Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy services stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175126929Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_academy-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175130273Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_api_rest_gateway-be80 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175133453Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_assess-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175136714Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_award-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175139914Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_grade-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175143138Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_ms_nodejs-be3002 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175146363Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_pc-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175152734Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_qual-web_nodejs-be3000 stopped (FE: 0 conns, BE: 0 conns).
2017-07-08T07:38:52.175628253Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Proxy config was reloaded
2017-07-08T07:38:52.175837320Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Creating configuration for the service development_ms_nodejs
2017-07-08T07:38:52.188064869Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 Reloading the proxy
2017-07-08T07:38:52.196657260Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy services started.
2017-07-08T07:38:52.196678990Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_academy-web_nodejs-be3000 started.
2017-07-08T07:38:52.196683302Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_api_rest_gateway-be80 started.
2017-07-08T07:38:52.196708213Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_assess-web_nodejs-be3000 started.
2017-07-08T07:38:52.196711998Z development_flow_proxy.1.u3bkzyujqih8@dev-m2    | 2017/07/08 07:38:52 HAPRoxy: Proxy development_award-web_nodejs-be3000 started.
2017-07-08T07:38:52.196715283Z development_flow_proxy.1

**Comment by AshleyAitken** [comment] 2017-07-08 17:22
Update all docker engines to 17.05 CE and now get something somewhat different:

2017-07-08T15:05:30.689475439Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:05:30 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_qual-web_nodejs&servicePath=%2Fqual
2017-07-08T15:05:30.689480184Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:05:30 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_grade-web_nodejs&servicePath=%2Fgrade
2017-07-08T15:05:30.689484792Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:05:30 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_academy-web_nodejs&servicePath=%2Facademy
2017-07-08T15:05:30.689489282Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:05:30 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3002&serviceName=development_ms_nodejs&servicePath=%2Fmock-webapi%2Fv0
2017-07-08T15:06:05.689373989Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=80&serviceName=development_api_rest_gateway&servicePath=%2Fwebapi%2Fv0: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:06:05.689466817Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_assess-web_nodejs&servicePath=%2Fassess: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:06:05.690074586Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3002&serviceName=development_ms_nodejs&servicePath=%2Fmock-webapi%2Fv0: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:06:05.690096976Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_qual-web_nodejs&servicePath=%2Fqual: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:06:05.690103929Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_grade-web_nodejs&servicePath=%2Fgrade: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:06:05.690110221Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_pc-web_nodejs&servicePath=%2Fpc: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:06:05.690116476Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_academy-web_nodejs&servicePath=%2Facademy: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:06:05.690145721Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:06:05 ERROR: Get http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=3000&serviceName=development_award-web_nodejs&servicePath=%2Faward: dial tcp 10.0.8.19:8080: i/o timeout
2017-07-08T15:26:22.638827980Z development_flow_listener.1.p9f1ef2zwcsn@dev-m1    | 2017/07/08 15:26:22 http: multiple response.WriteHeader calls

**Comment by vfarcic** [comment] 2017-07-08 17:43
One possible explanation is that you changed the names of services to something else but did not update their references so they cannot find each other. Can you send me the stack(s) you deployed?

If that's not the problem, it seems as if networking does not work. Swarm Listener is trying to send a request to the proxy and fails. Can you confirm that the name of the proxy service is `proxy` and that they are both inside the same network? If that's true, can you enter into Swarm Listener container and execute the commands that follow?

```bash
apk add --update drill
drill proxy
drill tasks.proxy
```

**Comment by AshleyAitken** [comment] 2017-07-09 03:15
Hi Viktor, thank you for Docker Flow and your assistance.  

I thought it looked like a networking and service resolution issue.  I changed the names of the services in the stack and tried again - it did not work.  I changed the names of the services in the stack back to the originals and now it works again.  

I've included the information you asked for FYI.

Cheers,
Ashley.


I have lots of stacks but here is the Docker Flow one:

version: "3.1"
# Docker Flow Proxy and Listener Compose File
#

services:

  # Docker Flow Proxy
  proxy:
#    image: vfarcic/docker-flow-proxy:latest
    image: vfarcic/docker-flow-proxy:${FLOW_PROXY_VERSION}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - system
    environment:
      - LISTENER_ADDRESS=listener
      - DEBUG=${DEBUG:-false}
      - MODE=swarm
    deploy:
      replicas: 1


  # Docker Flow Listener
  listener:
#    image: vfarcic/docker-flow-swarm-listener:latest
    image: vfarcic/docker-flow-swarm-listener:${SWARM_LISTENER_VERSION}
    networks:
      - system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:

  system:
    external: true

#
# EOF


Here is the output of the commands:

version: "3.1"
# Docker Flow Proxy and Listener Compose File
#

services:

  # Docker Flow Proxy
  proxy:
#    image: vfarcic/docker-flow-proxy:latest
    image: vfarcic/docker-flow-proxy:${FLOW_PROXY_VERSION}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - system
    environment:
      - LISTENER_ADDRESS=listener
      - DEBUG=${DEBUG:-false}
      - MODE=swarm
    deploy:
      replicas: 1


  # Docker Flow Listener
  listener:
#    image: vfarcic/docker-flow-swarm-listener:latest
    image: vfarcic/docker-flow-swarm-listener:${SWARM_LISTENER_VERSION}
    networks:
      - system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:

  system:
    external: true

#
# EOF

**Comment by AshleyAitken** [comment] 2017-07-09 03:16
Oops, the markdown misunderstood the comments in the compose file.

**Comment by vfarcic** [comment] 2017-07-10 11:50
I'm not sure what was the cause of the problem (maybe networking?). The stacks you used are the same as those I'm using in my cluster so it cannot be attributed to a type. Since now it works, I don't think we'll be able to find the cause unless it happens again. I'll close this ticket. Feel free to reopen it if you experience the same issue again.

**Closed by vfarcic** 2017-07-10 11:50 UTC
