### ISSUE TITLE
503 page when postgres stack deployed

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-proxy#285] opened 2017-07-10 16:01 UTC
I deployed my proxy:
```
version: "3.1"

networks:
  proxy:
      driver: overlay
      external:
        name: proxy

services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
```
Then my ci stack:

```
version: "3.1"

services:
  registry:
    image: registry:2.6.1
    ports:
      - "5000:5000"
    volumes:
      - registry:/var/lib/registry
    deploy:
      resources:
        reservations:
          memory: 100M

  master:
    image: jenkinsci/jenkins:${TAG:-lts-alpine}
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
      - ci
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080/jenkins -labels 'docker' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    networks:
      - ci
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      mode: global

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins:
    external: true
  registry:
    external: true

networks:
  proxy:
    external: true
  ci:
    driver: overlay
```

And then my db stack:
```
version: '3.1'

services:
  postgresql-master:
    image: 'bitnami/postgresql:9.6'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=${PG_REPL_PASS:-repl_password}
      - POSTGRESQL_USERNAME=odoo
      - POSTGRESQL_PASSWORD=${PG_ODOO_PASS:-odoo_pass}
      - POSTGRESQL_DATABASE=odoo
    volumes:
      - postgres:/opt/bitnami/postgresql
    networks:
      - postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.role == db-master'
      resources:
        reservations:
          cpus: '1'
          memory: 1G
  postgresql-slave:
    image: 'bitnami/postgresql:9.6'
    networks:
      - postgres
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=${PG_REPL_PASS:-repl_password}
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.role != db-master'
      resources:
        reservations:
          cpus: '.5'
          memory: 500M
  pgadmin:
    image: fenglc/pgadmin4:1.4
    networks:
      - postgres
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/pgadmin
        - com.df.port=5050
      placement:
        constraints:
          - 'node.labels.role != db-master'
volumes:
  postgres:
    external: true

networks:
  postgres:
    external: true

```
After deploying the ci stack, jenkins was available at /jenkins. After the db stack I got 503 page for /pgadmin and /jenkins, but the stats page was available. The service log for the proxy swarm listener:

proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:52:57 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8069&serviceName=core-services_odoo&servicePath=%2Fcrm
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:02 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5050&serviceName=core-db_pgadmin&servicePath=%2Fpgadmin
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:07 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8080&serviceName=ci_master&servicePath=%2Fjenkins
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:28 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8069&serviceName=core-services_odoo&servicePath=%2Fcrm
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:38 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8080&serviceName=ci_master&servicePath=%2Fjenkins returned status code 500
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.4 10.0.0.9]","ServiceName":"ci_master","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"IgnoreAuthorization":false,"Port":"8080","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/jenkins"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:38 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5050&serviceName=core-db_pgadmin&servicePath=%2Fpgadmin returned status code 500
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.9 10.0.0.4]","ServiceName":"core-db_pgadmin","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"IgnoreAuthorization":false,"Port":"5050","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/pgadmin"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:59 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8069&serviceName=core-services_odoo&servicePath=%2Fcrm returned status code 500
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.9 10.0.0.4]","ServiceName":"core-services_odoo","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"IgnoreAuthorization":false,"Port":"8069","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/crm"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}

**Comment by dave08** [comment] 2017-07-10 16:17
It looks like the postgres instance is constantly failing, maybe the tons of haproxy configuration updates, make it fail for other services...?

**Comment by dave08** [comment] 2017-07-10 17:09
The proxy is logging:

```
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | resolvers docker
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     nameserver dns 127.0.0.11:53
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | defaults
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     mode    http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     balance roundrobin
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     option  dontlognull
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     option  dontlog-normal
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     option  http-keep-alive
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     option  forwardfor
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     option  redispatch
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 400 /errorfiles/400.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 403 /errorfiles/403.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 405 /errorfiles/405.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 408 /errorfiles/408.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 429 /errorfiles/429.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 500 /errorfiles/500.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 502 /errorfiles/502.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 503 /errorfiles/503.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     errorfile 504 /errorfiles/504.http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     maxconn 5000
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     timeout connect 5s
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     timeout client  20s
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     timeout server  20s
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     timeout queue   30s
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     timeout tunnel  3600s
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     timeout http-request 5s
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     timeout http-keep-alive 15s
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | frontend services
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     bind *:80
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     bind *:443
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     mode http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     acl url_ci_master8080 path_beg /jenkins
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     use_backend ci_master-be8080 if url_ci_master8080
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     acl url_core-db_pgadmin5050 path_beg /pgadmin
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     use_backend core-db_pgadmin-be5050 if url_core-db_pgadmin5050
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | backend ci_master-be8080
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     mode http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     server ci_master ci_master:8080
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | backend core-db_pgadmin-be5050
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     mode http
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    |     server core-db_pgadmin core-db_pgadmin:5050
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 2017/07/10 17:08:41 Sending distribution request to http://10.0.0.4:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=5050&serviceName=core-db_pgadmin&servicePath=%2Fpgadmin
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 2017/07/10 17:08:41 Creating configuration for the service core-db_pgadmin
proxy_proxy.2.pbe6o0duy7b2@swarm-manager-02    | 2017/07/10 17:08:41 Reloading the proxy
proxy_proxy.1.g6sxtdfedu71@swarm-manager-01    | 2017/07/10 17:08:41 Sending distribution request to http://10.0.0.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=8080&serviceName=ci_master&servicePath=%2Fjenkins
proxy_proxy.1.g6sxtdfedu71@swarm-manager-01    | 2017/07/10 17:08:41 Creating configuration for the service ci_master
proxy_proxy.1.g6sxtdfedu71@swarm-manager-01    | 2017/07/10 17:08:41 Reloading the proxy

```

**Comment by dave08** [comment] 2017-07-10 17:25
Current logs for swarm listener (while above logs were appearing, with same config):

```
Fpgadmin
proxy_swarm-listener.1.mmsj8d2uncx1@swarm-manager-01    | 2017/07/10 17:22:14 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8080&serviceName=ci_master&servicePath=%2Fjenkins
proxy_swarm-listener.1.mmsj8d2uncx1@swarm-manager-01    | 2017/07/10 17:22:40 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5050&serviceName=core-db_pgadmin&servicePath=%2Fpgadmin
proxy_swarm-listener.1.mmsj8d2uncx1@swarm-manager-01    | 2017/07/10 17:22:40 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8080&serviceName=ci_master&servicePath=%2Fjenkins
proxy_swarm-listener.1.mmsj8d2uncx1@swarm-manager-01    | 2017/07/10 17:23:05 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5050&serviceName=core-db_pgadmin&servicePath=%2Fpgadmin returned status code 500
proxy_swarm-listener.1.mmsj8d2uncx1@swarm-manager-01    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.4 10.0.0.3]","ServiceName":"core-db_pgadmin","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"AllowedMethods":[],"DeniedMethods":[],"DenyHttp":false,"IgnoreAuthorization":false,"Port":"5050","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/pgadmin"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}
proxy_swarm-listener.1.mmsj8d2uncx1@swarm-manager-01    | 2017/07/10 17:23:05 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8080&serviceName=ci_master&servicePath=%2Fjenkins returned status code 500
proxy_swarm-listener.1.mmsj8d2uncx1@swarm-manager-01    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.3 10.0.0.4]","ServiceName":"ci_master","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"AllowedMethods":[],"DeniedMethods":[],"DenyHttp":false,"IgnoreAuthorization":false,"Port":"8080","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/jenkins"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}

```

**Comment by vfarcic** [comment] 2017-07-10 17:49
`pgadmin` cannot be reached by the proxy because they do not belong to the same networks. Can you please add `proxy` to the list of `pgadmin` networks and try again?

**Comment by vfarcic** [comment] 2017-07-29 20:44
@dave08 Can you please let me know whether we can close this issue?

**Comment by dave08** [comment] 2017-07-29 21:21
Technically, not being in the network was part of the problem, but there
was still some kind of intermittence afterwards, that caused me to docker
stack rm proxy it, and then have to redeploy. I think that when the
settings aren't good, for some reason they stay stuck. On production I
wouldn't easily be able to just recreate the stack... But for now all the
settings are ok and things are working so I can't recreate the problem,
that's why I didn't close it yet. But I guess I could always reopen it
(hopefully I won't have to if things keep on working😊).

בתאריך 29 ביולי 2017 11:44 PM,‏ "Viktor Farcic" <notifications@github.com>
כתב:

**Comment by vfarcic** [comment] 2017-07-29 21:34
Putting "wrong" labels might confuse the proxy. That might be the cause of the problem besides the obvious with the missing network.

I'll close this issue for now. Feel free to reopen it if you manage to reproduce the problem.

**Closed by vfarcic** 2017-07-29 21:34 UTC
