### ISSUE TITLE
Proxy doesn't react to changed IP and/or port for service in Consul

### ISSUE THREAD

**Issue by wilkko** [vfarcic/docker-flow-proxy#23] opened 2016-06-01 07:13 UTC
How to handle when information changes in Consul? I've seen that for example when you restart a container from Shipyard UI port might change and proxy is not able to follow and reconfigure proxy is required.

Normally I would run Consul template in daemon mode to solve this but don't know how Docker-flow-proxy is internally supposed to work.

**Comment by vfarcic** [comment] 2016-06-01 07:40
Docker Flow Proxy does not change automatically since it assumes that the change in service data is initiated by some process that, among other things, would send another request to reconfigure the proxy. The reason behind that is that in most cases we want to run tests that confirm that the change is indeed correct before making it visible to users through the proxy. Something like deploy/redeploy/scale > run tests > reconfigure the proxy if tests passed.

On the other hand, it would be relatively easy to add the option to reconfigure the proxy automatically if data related to a service changes in Consul. After all, the proxy uses Consul Template in background. There would be two additional request types (e.g. watchRegistry, stopWatchingRegistry). In such a case, you'd start by sending reconfigure request (as it is done now) followed by the watchRegistry request. From there on it would reconfigure the proxy every time Consul data changes until the stopWatchinRegistry is sent.

Please let me know if something like that would suit you.

**Comment by wilkko** [comment] 2016-06-01 09:35
> The reason behind that is that in most cases we want to run tests that confirm that the change is indeed correct before making it visible to users through the proxy. Something like deploy/redeploy/scale > run tests > reconfigure the proxy if tests passed.

But you are not supposed run the pre-deployment tests against the proxy (before reconfigure call has been made)?

**Comment by wilkko** [comment] 2016-06-01 09:41
What use case benefits from proxy being misconfigured with an invalid backend? e.g responding with 503. IP and port changes due to rescheduling when a node fails or port changes due to restarts are normal events in a Swarm or Nomad cluster.

**Comment by vfarcic** [comment] 2016-06-01 10:41
I used to have a process (Consul checks, Swarm events, etc) that would monitor services and react when something goes wrong or when the situation looks like something might be wrong in the future. Depending on the case, that reaction could be redeployment, scaling, sending emails, creating new nodes, and so on.

The problem is that I was so focused on the way I do things that I forgot that complicated processes like those might not be appropriate or desirable to everyone. You're right. In many cases people might need/want containers to be rescheduled and proxy reconfigured.

I'll work on this issue and come up a solution soon.

**Comment by vfarcic** [comment] 2016-06-01 11:58
Brainstorming a solution... How about a separate container that would monitor Swarm master logs (let's call it **monitor**)? If it detects that a container is rescheduled, it would send a request to Docker Flow Proxy to reconfigure itself. Such a solution would open a door for other interesting features. For example, if Swarm detects that a whole node is down, the **monitor** could run a user defined script that could create a new node. Or it could send an email or a chat message. What do you think?

**Comment by wilkko** [comment] 2016-06-01 12:40
Seperation of concern wise of course proxy should not be aware about anything else than the state for a service in the discovery service. What component then handles reacting to events in the cluster is not clear. To me only thing that is clear is that proxy should poll discovery service status. You would have to convince me otherwise =) If you look at Hashicorp's Nomad architecture and how it natively integrates with Consul, maybe you get some new insights to Docker flow design...

**Comment by vfarcic** [comment] 2016-06-01 12:54
That is true. However, one of my concerns is what to do with incorrect data in Consul. If, for example, you use Registrator to register services and one of the nodes fail, data registered for that node will stay in Consul until some other process removes them. Reconfiguring the proxy in such a case would result with config entries pointing to services that do not exist. That's not a big problem when the proxy has checks. It will skip the entries that do not return 200. Still, it's a bit "unclean".

On the other hand, you are right. Proxy should, probably, have auto-reconfigure inside itself.

**Comment by wilkko** [comment] 2016-06-01 13:03
I think proxy should trust that information in Consul/discovery service is correct.

**Comment by wilkko** [comment] 2016-06-01 13:13
> If, for example, you use Registrator to register services and one of the nodes fail, data registered for that node will stay in Consul until some other process removes them

Not a problem since Registrator can define Consul health checks and Consul will mark service unhealthy. By default Consul template will not serve unhealthy services so if proxy is polling that unhealthy service will be removed from proxy.

**Comment by wilkko** [comment] 2016-06-01 13:21
Consul health checks were the reason why I said earlier that HAProxy checks are not needed. But you could have them around for latency reasons. Consul marking a service unhealthy +1s, and Consul template polling consul +1s (or to whatever the poll interval is set) so it's not instant and some requests might end up in 503 without HAProxy checks.

**Comment by vfarcic** [comment] 2016-07-04 12:26
Just came back from DockerCon. With the new features that will be introduced in the new release 1.12, there will be no need for Consul since Docker SDN will take care of load balancing. That does not mean that Consul will dissapear (it will not), but that it will not be required for the proxy to deduce IPs and ports of running instances. I'll get back with more info and a new release soon.

**Comment by wilkko** [comment] 2016-08-04 11:38
I watched the Docker Con key notes and browsed through the Swarm mode and routing mesh documentation, but cannot get my head around how the external load balancer (API gateway) should be configured and how it routes specific paths to certain containers.

**Comment by vfarcic** [comment] 2016-08-04 11:46
Routing mesh will redirect a request no matter which server is hit. For example, if you run HAProxy in one of the servers inside the cluster and expose port 80, you can send a request to any node (not matter whether that's the one proxy is running or not). Routing mesh will pick it up and redirect it to any instance of a service that runs on port 80 (in this example HAProxy). On the other hand, most containers should not expose any port. In that case, you would have to make sure that they are in the same network as your proxy. Inside proxy configuration you would not list all the IPs of all the instances but only the service name.

Take a look at https://technologyconversations.com/2016/08/01/integrating-proxy-with-docker-swarm-tour-around-docker-1-12-series/ . I wrote it a few days ago.

**Comment by wilkko** [comment] 2016-08-04 11:59
Thanks. I'll take a look.

**Comment by wilkko** [comment] 2016-08-04 12:29
OK good, so the load balancer config has all the paths and they point to each service name and internal port (usually 8080). I have to upgrade and change the docker-flow-proxy to Swarm mode?
Swarm cluster needs to be redeployed with Docker 1.12 without Consul. Ansible doesn't seem to yet have support for docker swarm and docker service commands and CoreOS doesn't have Docker 1.12.

P.S. Don't you think default mode of docker-flow-proxy should still use consul template in deamon mode?

**Comment by vfarcic** [comment] 2016-08-04 13:02
You're right. As long as the proxy and a destination service belong to the same network, all you have to do (from proxy's perspective) is point to the service name and the port. There is no need to use "-p" argument.

Swarm cluster does need to run Docker 1.12. Basically, it is a completely different Swarm. The only thing it shares in common with the old Swarm is the name.

I'm not sure what you mean by Ansible not supporting Docker Swarm (the new one). All you have to do is install Docker and initialize/join Swarm. It's one "apt" and one "shell" task.

As for CoreOS, I haven't used it in a while. Can you update Docker version in it?

P.S. I should use change the proxy to use Consul Template in deamon mode. It's just that I put it low on my priority list. I'm spending most of my time trying to figure out tips and tricks with the new Swarm. Also, I don't think there will be many old Swarm users in the future. Docker will not continue developing it so it's a dead-end. The future is the new Swarm (or "Swarm mode" as some call it).

**Comment by wilkko** [comment] 2016-08-04 13:21
In CoreOS you cannot upgrade (I think) Docker unless you upgrade the image itself. That's actually good that they test Docker before releasing new images. Current alpha image is in Docker 1.11.2 so might have to test with Ubuntu in the mean while.

For Ansible would be nice to have module support for the new Docker service and swarm APIs without having to create custom scripts that would call bash command, because it's hard to make them idempotent etc.
https://github.com/ansible/ansible/blob/devel/docsite/rst/guide_docker.rst
Might consider switching into using Cloud formation to create the Swarm cluster.

**Comment by vfarcic** [comment] 2016-08-04 13:28
If you're in AWS, you might want to try "Docker for AWS". Please note that it's still in beta.

Personally, when using cloud providers, I use Packer to create images (AMIs), Ansible to provision them, and Terraform to instantiate. Since some information is not available when creating AMIs, Terraform usually does initializations as well. In case of the new Swarm, Packer/Ansible create AMI with Docker and whatever else is needed, and Terraform creates as many instances as I need. When an instance is created, Terraform also runs "docker swarm init" or "docker swarm join". In such a combination, idempotency is not important since I don't try to maintain servers in the "correct" state. I usually kill them and create new ones whenever I need something.

**Comment by vfarcic** [comment] 2016-09-17 20:33
Closing due to inactivity. Please reopen this ticket if you think there is still some pending task to be done.

**Closed by vfarcic** 2016-09-17 20:33 UTC
