### ISSUE TITLE
[Swarm mode] Auto-configuration based on service labels

### ISSUE THREAD

**Issue by bvis** [vfarcic/docker-flow-proxy#44] opened 2016-09-20 14:22 UTC
One option that would be very interesting would be about the usage of labels in the service to define some characteristics like:

- I want to be accessible from the 80/443 port
- I want to get traffic from this path and/or this domain.
- Autoconfiguration of the TLS certificate

For example, if I launch a service with something like:
```
docker service create \
  --label "com.proxy.flow.http=80" \
  --label "com.proxy.flow.path=/" \
  --label "com.proxy.flow.domain=go-demo.com" \
  --label "com.proxy.flow.key=TLSKEYHERE" \
  --label "com.proxy.flow.cert=TLSCERTHERE" \ 
  -p 80 \
  --network flow-proxy \
   --name nginx-public \
  nginx
```
Then, in a similar way consul-template does over consul events, the docker-flow-proxy or a complementary service hearing for docker events could catch those services with these labels and automatically publish the service named *nginx-public* for the go-demo.com domain under the "/" path.

This would allow to launch many services in Docker swarm with just one load balancer over the entire cluster.

An important point is that when a new instance of the proxy is started it should do an initial check of the services that have any of its labels, to initialise the proxy status.

This allows the proxy to not to need any backend server because the status is already provided by the swarm cluster.

**Comment by vfarcic** [comment] 2016-09-27 01:32
The first version of a possible solution is done. It runs as a separate container. Please see the info in the [Swarm Listener](https://github.com/vfarcic/docker-flow-swarm-listener) project.

The next step would be to implement the missing features from this request inside the proxy (TLS and initial check). Before I switch to the proxy, I'd appreciate if you give it a try and let me know whether the direction I'm taking looks OK.

**Comment by bvis** [comment] 2016-09-30 14:31
Hi,
I think your approach, separating the listening feature in another service, is a good idea.
I've tested it and I see that it works as expected, and the reconfiguration time is almost immediate!

I've had a problem when trying to reconfigure a service and I missed the label "com.df.servicePath", now I see it is mandatory even when you just want to configure the domain using the "com.df.serviceDomain" label, but this is not an important issue.

I think that's the right direction. Good job!

### Other considerations
Now it's time for the wishlist, maybe some of my suggestions are not feasible or could be done on another way.

Now I have some concerns about the HA provided by the service. It now has 2 components, when I tried to scale the number of swarm-listeners to 2 it worked as expected, both tried to configure the only task running the docker-flow-proxy image. I don't know if this could be an issue but I haven't seen any race condition.

One thing I'm missing is that when a service is removed its entry remains in the proxy. A possible improvement would be to remove the entries that do't belong to any active service, it should be simple to implement using the existing "remove" API endpoint.

### Self-configuration feature (without the need of any external KV store)
Another improvement allowing the service to provide full HA would be to add an autoconfiguration layer in the docker-flow-proxy image, instead of save its status in an external service like consul. It could be done following the next steps:

1. The swarm-listener send a request to the proxy reconfigure endpoint.
2. One task of the service receives this request and before committing it locally starts a "distributed transaction" phase*.
3. As each task knows itself and can obtain the other tasks that are running on the service (_nslookup tasks.swarm-listener | grep -v $(hostname)_ as example) just loop over all the other service tasks and throw the same request
4. If all the tasks return OK the service change can be committed locally and returned to user.

Of course this means that each time a new proxy task is launched it needs to autodiscover another task and initialise itself from its config before being "healthy".

* In the future this could be done adding a two-steps commits algorithm like Raft or Paxos. Initially a simple loop as described could be done as PoC.

**Comment by bvis** [comment] 2016-09-30 14:34
I think this can be closed. If you want I can create other issues related with any of the functionalities, just let me know.

Thanks again for your work!

**Comment by vfarcic** [comment] 2016-10-01 19:53
> Now I have some concerns about the HA provided by the service. It now has 2 components, when I tried to scale the number of swarm-listeners to 2 it worked as expected, both tried to configure the only task running the docker-flow-proxy image. I don't know if this could be an issue but I haven't seen any race condition.

The proxy was designed with race conditions in mind. Unless there is a bug, it should be able to handle multiple parallel requests even if they are the same.

I'm not sure whether there is a new for two instances of swarm-listeners. If one fails, Swarm will reschedule it somewhere else. During that short period of time (between the failure and until it is rescheduled), new service will not be reconfigured. However, new services are created with very low frequency. Most of the time we update them and that does not require proxy reconfiguration. Even if a new service is created at the same time as the listener fails, it would still not mean any downtime for the service since it is the first release and users do not expect to see it immediately.  On the other hand, if there is a need for multiple instances of the listener, the only downside is that multiple requests will be sent to the proxy producing a very low and infrequent network traffic increase.

Yes. Please create other issues so that we can track them down. Closing this one...

**Comment by vfarcic** [comment] 2016-10-01 19:54
> One thing I'm missing is that when a service is removed its entry remains in the proxy. A possible improvement would be to remove the entries that don't belong to any active service, it should be simple to implement using the existing "remove" API endpoint.

That is still missing. Can you please open an issue so that we track it better?

**Comment by vfarcic** [comment] 2016-10-01 19:55
> Self-configuration feature (without the need of any external KV store)

That would, indeed, be a good addition. Can you please open an issue so that we track it better?

**Closed by vfarcic** 2016-10-01 19:55 UTC
