### ISSUE TITLE
How to track down ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Vad1mo** [vfarcic/docker-flow-proxy#416] opened 2018-01-25 17:48 UTC
I have an issue where every 1 of 10 request receives an ERR_SSL_PROTOCOL_ERROR. Now I want to track down this issue however there aren't anything in the DFP logs.

How can we track down this sporadic error?

We have a bit of a special setup with an TCP LB in front of DFP (3 Nodes) the TCP LB is configured in Round Robin with Source IP sticky session. So each request should go to the same DFP node.

**Comment by vanbroup** [comment] 2018-01-25 19:07
We look to have a similar issue but without any TCP LB in front, in this setup, we have a three-node swarm cluster.  With a simple curl loop that makes a request to one specific node in the cluster, you can clearly see the problem.

(ip address and hostname redacted)
```
while :; do
        i=$((i + 1))
        echo $i `curl -sS --tlsv1.2 --resolve redacted.example.com:443:1.2.3.4 https://redacted.example.com`
        sleep 2
done
```

Result:
```
1 404 page not found
2 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
3
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
4
5 404 page not found
6 404 page not found
7 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
8
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
9
10 404 page not found
11 404 page not found
12 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
13
14 404 page not found
15 404 page not found
16 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
17
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
18
19 404 page not found
20 404 page not found
```

**Comment by Vad1mo** [comment] 2018-01-25 21:56
Interesting, exactly the same error.  We have 3 worker nodes each running a DFP instance. We  @nib0r `docker-flow-proxy-letsencrypt` to get our certs that we store in cinder fs and swarm secrets.  Our Cluster is running on OpenStack.

Error:
```
curl https://ci.8gears.com
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
> curl https://ci.8gears.com
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
> curl https://ci.8gears.com
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
> curl https://ci.8gears.com
  <!DOCTYPE html><html><head resURL="/static/ff25c403" data-rooturl="" data-resurl="/static/ff25c403">
```

I will bypass the LB and try to  reproduce the error, I think this should be reproducible. 

CI Jenkins config for DFP.

```
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=8080
        - com.df.serviceDomain=ci.8gears.com
        - com.df.letsencrypt.host=ci.8gears.com
        #- com.df.redirectWhenHttpProto=true
        - com.df.httpsOnly=true
        - com.df.httpsRedirectCode=301
        #- com.df.srcPort=443
        - com.df.letsencrypt.email=le@8gears.com
```

Here is our proxy config, nothing fancy
```
version: "3.4"
services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - SERVICE_NAME=proxy_proxy
      # - DEFAULT_PORTS=80 accept-proxy,443 accept-proxy:ssl
    deploy:
      mode: global
      # replicas: 1
      placement:
        constraints: [node.role == worker]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy-le:8080/v1/docker-flow-proxy-letsencrypt/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy_proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy-le:
    image: nib0r/docker-flow-proxy-letsencrypt
    networks:
      - net
    environment:
      - DF_PROXY_SERVICE_NAME=proxy_proxy
      # - LOG=debug
      # - CERTBOT_OPTIONS=--staging
    volumes:
      # link docker socket to activate secrets support.
      - /var/run/docker.sock:/var/run/docker.sock
      # create a dedicated volume for letsencrypt folder.
      # MANDATORY to keep persistent certificates on DFPLE.
      # Without this volume, certificates will be regenerated every time DFPLE is recreated.
      # OPTIONALY you will be able to link this volume to another service that also needs certificates (gitlab/gitlab-ce for example)
      - le-certs:/etc/letsencrypt
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]      
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.port=8080
networks:
  net:
volumes:
   le-certs:
    driver: cinder
    driver_opts:
      size: 1

```

**Comment by Vad1mo** [comment] 2018-01-25 22:01
Searching on the internet I found some references:


> It appears there is no SSL/TLS server listening on 10.0.10.90:50060. There is a server listening, its just not SSL/TLS. [ref](https://stackoverflow.com/questions/21135637/error140770fcssl-routinesssl23-get-server-hellounknown-protocol)



Reproducible be trying to establish a TLS connection to an HTTP endpoint. e.g.
```
curl https://ci.8gears.com:80
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by vanbroup** [comment] 2018-01-26 09:07
We are using docker secrets to store the pem files and regular publicly trusted EV certificates. I have redeployed the proxy stack and found that the problem became much less frequent.

I also upgraded the docker compose file to version 3.1 and added the secret ids to the `secrets` section so that the proxy can always access the certificates.

Also, and probably more closely related to the problem I found one service that was not connected to the proxy overlay network, this looked to have caused some issues with `could not resolve address` resulting in the proxy to fail to start with `Failed to initialize server(s) addr.`. The strange thing is that this misconfigured service was working fine? But maybe with instances frequently restarting this could have caused the random errors.

I'm not sure how often the ha-proxy is restarted for updates but I feel strongly that this is related to the problem and it might be interesting to see if **seamless reloads** can be configured for docker flow proxy?

https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/

**Comment by Vad1mo** [comment] 2018-01-26 09:26
@vanbroup, It almost looks we are working on the swarm cluster. 

I also see `ould not resolve address` and `Failed to initialize server(s) addr.`  this seems to cause problems to DFP. We are using OpenFass that has a few dozens of containers. After removing the stack it got a bit better.

Can you post an example regarding your **secrets** section and ids. I couldn't find anything on the net.

**Comment by Vad1mo** [comment] 2018-01-26 09:28
@vfarcic are  **seamless reloads** on the roadmap of DFP or are they already included?

**Comment by vanbroup** [comment] 2018-01-26 09:58
Hi @Vad1mo, here is a redacted version of my config:

```
version: "3.1"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - STATS_USER=adminuser
      - STATS_PASS=adminpassword
      - STATS_URI=/proxy/stats
      - SKIP_ADDRESS_VALIDATION=false
      - RECONFIGURE_ATTEMPTS=5
      - HTTPS_ONLY=true
    secrets:
      - cert_www.example.com
      - cert_www.example2.com
    deploy:
      mode: global

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true

secrets:
  cert_www.example.com:
    external: true
  cert_www.example2.com:
    external: true

```

**Comment by vanbroup** [comment] 2018-01-26 09:59
I did some ab benchmarks to check when and how often requests are failing under some more realistic request volume and noticed that **when I make 1000 requests 250 requests will fail, always**!

```
# ab -n 1000 https://www.example.com/proxy/stats

This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.example.com (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        www.example.com
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256

Document Path:          /proxy/stats
Document Length:        112 bytes

Concurrency Level:      1
Time taken for tests:   44.527 seconds
Complete requests:      1000
Failed requests:        250
   (Connect: 0, Receive: 0, Length: 250, Exceptions: 0)
Non-2xx responses:      1000
Total transferred:      239000 bytes
HTML transferred:       88500 bytes
Requests per second:    22.46 [#/sec] (mean)
Time per request:       44.527 [ms] (mean)
Time per request:       44.527 [ms] (mean, across all concurrent requests)
Transfer rate:          5.24 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       31   34  31.6     33    1033
Processing:     9   10   6.7     10     222
Waiting:        9   10   6.7     10     222
Total:         40   44  32.4     43    1043

Percentage of the requests served within a certain time (ms)
  50%     43
  66%     44
  75%     44
  80%     44
  90%     45
  95%     45
  98%     46
  99%     47
 100%   1043 (longest request)
```

I did run this test many times, even with different concurrencies, but exact 250 requests fail.
```
# ab -n 1000 https://www.example.com/proxy/stats

This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.example.com (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        www.example.com
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256

Document Path:          /proxy/stats
Document Length:        112 bytes

Concurrency Level:      500
Time taken for tests:   1.261 seconds
Complete requests:      1000
Failed requests:        250
   (Connect: 0, Receive: 0, Length: 250, Exceptions: 0)
Non-2xx responses:      1000
Total transferred:      239000 bytes
HTML transferred:       88500 bytes
Requests per second:    792.95 [#/sec] (mean)
Time per request:       630.554 [ms] (mean)
Time per request:       1.261 [ms] (mean, across all concurrent requests)
Transfer rate:          185.07 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       37  104 204.3     54    1060
Processing:     9   14   6.8     11      62
Waiting:        9   13   5.4     11      44
Total:         49  118 204.5     69    1087

Percentage of the requests served within a certain time (ms)
  50%     69
  66%     78
  75%     87
  80%     93
  90%    117
  95%    129
  98%   1064
  99%   1072
 100%   1087 (longest request)
```

@Vad1mo can you try this on your cluster?

**Comment by vanbroup** [comment] 2018-01-26 10:40
It looks to be quite stable for me at the moment:
```
ab -c 1000 -n 10000 https://www.example.com/
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.example.com (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:
Server Hostname:        www.example.com
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256

Document Path:          /
Document Length:        18 bytes

Concurrency Level:      1000
Time taken for tests:   12.885 seconds
Complete requests:      10000
Failed requests:        0
Non-2xx responses:      10000
Total transferred:      1760000 bytes
HTML transferred:       180000 bytes
Requests per second:    776.13 [#/sec] (mean)
Time per request:       1288.452 [ms] (mean)
Time per request:       1.288 [ms] (mean, across all concurrent requests)
Transfer rate:          133.40 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       32  239 796.9     46    7097
Processing:    10   26  21.8     20     286
Waiting:        9   25  21.4     18     284
Total:         45  266 799.3     66    7182

Percentage of the requests served within a certain time (ms)
  50%     66
  66%     76
  75%     87
  80%     97
  90%    373
  95%   1091
  98%   3085
  99%   3163
 100%   7182 (longest request)
```

**Comment by Vad1mo** [comment] 2018-01-28 08:44
right now this is are my results: 1643 failed out of 10000 or **16%**
This is pretty much stable no matter what service I test against. 

```
docker run --rm mocoso/apachebench ab -n 10000 -c 1000 https://staticpage.domain.com/
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking staticpage.domain.com (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        staticpage.domain.com
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256

Document Path:          /
Document Length:        2704 bytes

Concurrency Level:      1000
Time taken for tests:   17.330 seconds
Complete requests:      10000
Failed requests:        1643
   (Connect: 0, Receive: 0, Length: 1643, Exceptions: 0)
Non-2xx responses:      1643
Total transferred:      25534893 bytes
HTML transferred:       23540410 bytes
Requests per second:    577.04 [#/sec] (mean)
Time per request:       1732.983 [ms] (mean)
Time per request:       1.733 [ms] (mean, across all concurrent requests)
Transfer rate:          1438.93 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       61 1056 2018.3    674   16383
Processing:    38  382 115.7    396    1360
Waiting:       19  188  60.7    190    1221
Total:        178 1438 2045.2   1091   17293

Percentage of the requests served within a certain time (ms)
  50%   1091
  66%   1112
  75%   1222
  80%   1329
  90%   1795
  95%   2088
  98%   8265
  99%  16844
 100%  17293 (longest request)

```

**Comment by vanbroup** [comment] 2018-01-28 09:43
@Vad1mo they fail at content length, not on the connection. You actually have 0 connection failures:

> Failed requests:        1643
>    (Connect: 0, Receive: 0, Length: 1643, Exceptions: 0)

**Comment by Vad1mo** [comment] 2018-01-29 11:49
Hmm, true. It seems to be quite now after I created a completely new cluster. I still have no clue what was the cause of the problem. However I leave this thread open for a few days to see if I can reproduce the issue.

**Comment by vanbroup** [comment] 2018-01-29 14:01
I think this has something to do with a syncing/config validation issue of individual proxies, even now our problems look to have resolved by reinstalling the docker flow proxy that doesn't mean the problem is resolved or is not coming back. I'm concerned that this issue might come back after updating or provisioning services on the cluster.

**Comment by Vad1mo** [comment] 2018-01-29 14:08
for us this is a big setback, as we now can't switch to the new swarm cluster. We need to do more testing and slowly start migrating test environments first.

**Comment by Vad1mo** [comment] 2018-02-02 07:25
Here we are again, 5 days later.

```
docker run mocoso/apachebench ab -n 1000 -c 100 https://cloud.8gears.com/                                 
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cloud.8gears.com (be patient)
SSL handshake failed (1).
139784565528344:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
SSL handshake failed (1).
139784565528344:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
SSL handshake failed (1).
139784565528344:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
SSL handshake failed (1).
139784565528344:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
SSL handshake failed (1).
139784565528344:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
....
```

So the cluster was more or less idling for 4 days until yesterday. 

A faulty (test) service was deployed that constantly retried to start and failed. The stack was removed after a few hours. All nodes where and are operational. On the surface everything looks as usual.

**Comment by Vad1mo** [comment] 2018-02-03 16:25
Not sure if this is of any help
But after the TLS error we also see this type of issues as well

```
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node qt1c6dvmddodkoypzqxql2unv is not available
```

**Comment by vfarcic** [comment] 2018-02-03 17:48
Do you think there is a way to reproduce this issue? I'm failing to grasp what the problem might be. If I could reproduce it somehow, I might be able to figure out the cause.

**Comment by Vad1mo** [comment] 2018-02-03 17:53
I can setup a test cluster and and deploy some test apps. I than can give you access to the nodes. So you could take a look at an actual instance. 

I am not sure if we can reproduce it in vagrant. Maybe this is IaaS provider related. @vanbroup who is you IaaS provider?

**Comment by vanbroup** [comment] 2018-02-04 07:04
OVH (OpenStack) based.

I still strongly feel that it had something to do with nodes that keep reloading their config. Because of a (previous) misconfiguration.

**Comment by Vad1mo** [comment] 2018-02-04 10:16
Our Testcluster is also at OVH.(Not sure if that is really a pure coincidence) @vanbroup you can ping me on [https://devops20.slack.com/messages/D8XTC8L2C][1]

Meanwhile I'll setup a new dedicated cluster and reproduce the error. I am becoming pretty good at it.

[1]: https://devops20.slack.com/messages/D8XTC8L2C

**Comment by Vad1mo** [comment] 2018-02-06 10:17
The error indicates that a TLS request to a HTTP endpoint? Can it be that the swarm cluster is degraded and can deliver the certs in time? I am trying to understand in what circumstances DFP is service HTTP instead of TLS.

**Comment by WolfspiritM** [comment] 2018-02-20 08:18
I'm currently running into a similar issue but not sure if it's related.
I have docker-flow-proxy deployed together with hamburml/docker-flow-letsencrypt.
Whenever I do an update to the proxy (like adding an env-var for configuration) so it has to restart it doesn't seem to pull the certificate informations anymore and I get:
```
2018/02/20 08:07:47 HAPRoxy: 178.31.43.13:63722 [20/Feb/2018:08:07:47.818] services services/<NOSRV> -1/-1/-1/-1/0 400 658 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>"
```
With a ERR_SSL_PROTOCOL_ERROR.

When I then do a "docker stack rm proxy" and a new "docker stack deploy..." everything works again.

**Comment by vfarcic** [comment] 2018-04-18 10:53
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.

**Closed by vfarcic** 2018-04-18 10:53 UTC
