### ISSUE TITLE
2 HAProxy after reload

### ISSUE THREAD

**Issue by morsik** [vfarcic/docker-flow-proxy#403] opened 2017-12-28 10:43 UTC
**Description**

This looks like critical, but I'm not sure why is that (maybe bug in HAProxy 1.8?)

**Steps to reproduce the issue:**
Don't know how... Tonight letsencrypt-companion reloaded certs, and I started getting SSL problems. After some digging I found this:
```
 # ps auxf | grep haproxy
root     15446  0.0  0.4  19192  7068 ?        Ss   Dec25   0:21  |   |       \_ haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 10
root     18587  0.0  0.4  19488  7208 ?        Ss   04:00   0:02  |   |       \_ haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 31393
```

I killed older one, and everything is OK now.
I found this state on all hosts where proxy is running, and on all new haproxy has "04:00" starttime (the time when DFLE was doing something with certs).

**Describe the results you received:**
2 HAProxy where older is misconfigured

**Describe the results you expected:**
Should be 1 here with correct config.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have 3 docker hosts, and proxy is set to `global` mode, so I have 1 proxy each node. I'm switching IP between hosts when needed (for HA).

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Own VMs (CentOS 7 + Docker 1.13 from Docker repository).

**Comment by vfarcic** [comment] 2017-12-28 12:33
That is indeed critical. The problem is to reproduce it. Do you have a clue that might help?

**Comment by vfarcic** [comment] 2018-01-28 16:39
@morsik I could not reproduce it. Did you have any luck reproducing the issue or was it a one-time thing?

**Comment by morsik** [comment] 2018-01-29 00:14
Unfortunately I was unable to reproduce that :(

**Comment by vfarcic** [comment] 2018-01-29 13:23
I'll close it for now as not reproducible. Feel free to reopen it if you manage to reproduce it.

**Closed by vfarcic** 2018-01-29 13:23 UTC
