### ISSUE TITLE
Accommodating session affinity for services running in swarm behind DFP

### ISSUE THREAD

**Issue by michaelwilde** [vfarcic/docker-flow-proxy#171] opened 2017-03-09 20:32 UTC
it is understood that Docker Swarm's routing mesh is an IPVS (layer 4) routing mesh.   HAProxy exists at layer 7.  In the current implementation, when an HTTP request is proxied to a stateless backend service (especially with a replica count> 1), everything works just fine.   

When stateful services are used.. often cookies are dropped on the user's browser to tie the session to an IP/HOST that are used to respond to future HTTP/S requests and maintain state and time..  When one takes a stateful service (example a Splunk Search Head), launches it inside of a Docker service, and changes the replica count to > 1, Docker's routing mesh (existing at L4) may, and will likely send the requesting proxy server a different IP and sending the user to a different container for each request.   This of course causes confusion, errors and potentially other badness.

Could we take and bring the entire conversation up to Layer 7 so the Docker Flow: Proxy could accommodate something like this?  Here are some ideas

add one more more com.df labels, like
--com.df.sessiontype=sticky (could be others)

1.  "swarm-listener" - give swarm listener an extra job.  That job would be to, if the session type is set, interrogate the tasks on a service (upon every "event"), find the VIP for each container/task that running in the service.
2.  "swarm-listener" - upon service discovery, notify the HAProxy container with backend service of the container name/ip:port and perhaps some specified cookie name if necessary.
3. "proxy" - ensures that session affinity/stickiness makes client get proxied to the same backend container as needed.

This would pull the transaction all the way up to layer 7, maybe allowing swarm itself to accommodate more traditional stateful web applications where session affinity is required.

An interesting HAProxy blog post about the topic:  http://blog.haproxy.com/2012/03/29/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/

**Comment by michaelwilde** [comment] 2017-07-29 03:01
@vfarcic thoughts?  possible?

**Comment by vfarcic** [comment] 2017-07-29 11:31
@michaelwilde First of all, I'm sorry for ignoring this ticket for so long. It can be done. The only problem is time. I never seem to have enough of it. I'll start working on a draft ASAP.

**Comment by vfarcic** [comment] 2017-07-29 19:16
The first draft of the feature is finished. I'd appreciate if you could try it out and let me know whether it works as you expected and whether you have any suggestions for improvement. The official release and documentation will follow once I get your feedback.

You'll find my manual tests in https://github.com/vfarcic/docker-flow-proxy/tree/issue-171/issues/171. The README contains short instructions. The stack I used in the same directory. Please use it as a way to understand the feature and test it using your own commands and/or services. That would provide more variety to the tests.

Please note that I did not yet test whether sticky sessions work. They should but, until now, I was mostly focused on discovery of addresses of each replica.

**Comment by vfarcic** [comment] 2017-08-01 11:53
@michaelwilde Did you have time to try it out?

**Comment by michaelwilde** [comment] 2017-08-01 16:46
Will do within the next day

Get Outlook for iOS<https://aka.ms/o0ukef>



On Tue, Aug 1, 2017 at 4:53 AM -0700, "Viktor Farcic" <notifications@github.com<mailto:notifications@github.com>> wrote:


@michaelwilde<https://github.com/michaelwilde> Did you have time to try it out?

-

**Comment by michaelwilde** [comment] 2017-08-09 05:23
It is configuring a server in the proxy for each replica.. thats good.   not responding on the front end, but thats probably me missing new features since 1.3

**Comment by michaelwilde** [comment] 2017-08-09 06:28
Hmm... check this out.  All works just fine in 1.393.  Did some syntax change that i missed?

```
version: "3.1"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:1.393
    ports:
      - 80:80
      - 8000:8000
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BIND_PORTS=8000
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:latest
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  docs:
    image: vfarcic/docker-flow-proxy-docs
    hostname: proxydocs
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=proxydocs.demo.splunkoxygen.com
        - com.df.serviceDomainMatchAll=true
        - com.df.srcPort.1=80
        - com.df.servicePath=/
        - com.df.port=80
        - com.docker.ucp.access.label=production
        - com.docker.ucp.access.owner=mwilde
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  proxy:
    external: true
```

In :latest, or :issue-171 I'm noticing the "fe" files all become empty.

```
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 8000:8000
      - 8080:8080
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BIND_PORTS=8000
      - REPEAT_RELOAD=true
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  docs:
    image: vfarcic/docker-flow-proxy-docs
    hostname: proxydocs
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=proxydocs.demo.splunkoxygen.com
        - com.df.serviceDomainMatchAll=true
        - com.df.srcPort=80
        - com.df.servicePath=/
        - com.df.port=80
        - com.df.sessionType=sticky-server
        - com.docker.ucp.access.label=production
        - com.docker.ucp.access.owner=mwilde
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  proxy:
    external: true
```

**Comment by vfarcic** [comment] 2017-08-09 11:41
I deployed that stack and the proxy configuration looks OK. If you're referring to proxy_docs-fe.cfg being empty, quite some time ago I removed files to create front-end config snippets. The idea is that everything should be in memory.

Can you please let me know whether the proxy configuration (`/cfg/haproxy.cfg`) is generated as expected?

**Comment by michaelwilde** [comment] 2017-08-10 01:10
@vfarcic the haproxy.cfg is getting written...but there are some differences.  Specifically, hdr_dom(host) is shown in 1.393, but hdr_dom is shown in latest.  Is the missing **(host)** the issue?

I notice in 1.393 I see

` bind *:8000                                                                                                                                    
    acl url_splunkoxygen-ops_deployer8000 path_beg \/                                                                                              
    acl domain_splunkoxygen-ops_deployer hdr_dom(host) -i deployer.demo.splunkoxygen.com                                                           
    use_backend splunkoxygen-ops_deployer-be8000 if url_splunkoxygen-ops_deployer8000 domain_splunkoxygen-ops_deployer                             
    acl url_DockerFlow_docs80 path_beg /                                                                                                           
    **acl domain_DockerFlow_docs hdr_dom(host) -i proxydocs.demo.splunkoxygen.com**                                                                    
    use_backend DockerFlow_docs-be80 if url_DockerFlow_docs80 domain_DockerFlow_docs                                                               
    acl url_demo-3clicks1beer_demoindexer8000 path_beg /                                                                                           
    acl srcPort_demo-3clicks1beer_demoindexer8000 dst_port 8000                                                                                    
    acl url_demo-3clicks1beer_demoindexer8080 path_beg /                                                                                           
    acl srcPort_demo-3clicks1beer_demoindexer80 dst_port 80                                                                                        
    acl domain_demo-3clicks1beer_demoindexer hdr_dom(host) -i www.3clicks1beer.com              `

and in :latest :issue-171 I see this.

`    bind *:8000                                                                                                                                                                                                
    acl url_DockerFlow_docs80_0 path_beg /                                                                                                                                                                     
    acl srcPort_DockerFlow_docs80 dst_port 80                                                                                                                                                                  
    **acl domain_DockerFlow_docs80_0 hdr_dom -i proxydocs.demo.splunkoxygen.com**                                                                                                                                  
    use_backend DockerFlow_docs-be80_0 if url_DockerFlow_docs80_0 domain_DockerFlow_docs80_0 srcPort_DockerFlow_docs80                                                                                         
    acl url_demo-3clicks1beer_demoindexer8000_1 path_beg /                                                                                                                                                     
    acl srcPort_demo-3clicks1beer_demoindexer8000 dst_port 8000                                                                                                                                                
    acl domain_demo-3clicks1beer_demoindexer8000_1 hdr_dom -i www.3clicks1beer.com                                                                                                                             
    acl url_demo-3clicks1beer_demoindexer8080_2 path_beg /                                                                                                                                                     
    acl srcPort_demo-3clicks1beer_demoindexer80 dst_port 80                                                                                                                                                    
    acl domain_demo-3clicks1beer_demoindexer8080_2 hdr_dom -i www.3clicks1beer.com     `

**Comment by vfarcic** [comment] 2017-08-10 02:18
You're right. I deprecated `serviceDomainMatchAll` in favor of `serviceDomainAlgo` parameter. It gives more flexibility to define algorithm for matching domains. Even though `serviceDomainMatchAll` was removed from docs, I'm keeping it in the code so that backwards compatibility is maintained. The issue is that I made a mistake in that part of the code. Now it should be fixed. Can you please try the tag `vfarcic/docker-flow-proxy:17.08.10-23`?

**Comment by vfarcic** [comment] 2017-08-24 16:00
I'll assume that the main objective of this issue is fulfilled and close it. Please reopen if you feel that something is missing.

**Closed by vfarcic** 2017-08-24 16:00 UTC
