### ISSUE TITLE
Haproxy log

### ISSUE THREAD

**Issue by aaron0428** [vfarcic/docker-flow-proxy#175] opened 2017-03-11 02:05 UTC
I am sorry, because I am in China, I just received an e-mail, your URL address (http://proxy.dockerflow.com/haproxy.tmpl) can not open. Then, I still have a question, how to HAPROXY log output to the file, so that I can always view in the docker-flow-proxy!

**Comment by vfarcic** [comment] 2017-03-11 19:35
Closing this issue as a duplicate of https://github.com/vfarcic/docker-flow-proxy/issues/167. It contains the same comment.

**Closed by vfarcic** 2017-03-11 19:35 UTC
