### ISSUE TITLE
Force https redirection

### ISSUE THREAD

**Issue by Loyz07** [vfarcic/docker-flow-proxy#132] opened 2017-02-08 17:02 UTC
Hello,

Is there a way to force redirection from http to https in docker-flow-proxy parameters ?

I.e add the line below in haproxy frontend configuration:
- for all domains: redirect scheme https code 301 if !{ ssl_fc }
- for one domain: redirect scheme https if { hdr(Host) -i www.mydomain.com } !{ ssl_fc }

I think it would be a good idea to add a config parameter to the docker service creation to set this redirection like this:
--label com.df.forceHttps=true 

For discussion.
Thanks.

**Comment by hamburml** [comment] 2017-02-08 17:05
You can set `httpsOnly` as label on a service. See http://proxy.dockerflow.com/usage/ and search for httpsOnly.

**Comment by Loyz07** [comment] 2017-02-08 17:53
Amazing.

You're really an awesome team !

Thanks.

**Comment by shabbirkagalwala** [comment] 2017-07-18 20:48
Sorry for opening/commenting on this issue again but when using httpsOnly our webiste throws an error saying too many redirects? Any suggestions would help. Thank you.

**Comment by vfarcic** [comment] 2017-07-18 21:04
@shabbirkagalwala Can you post the stack you're using? That might give me an insight into the behavior you're experiencing. If possible, it would be great if you could reproduce it with public services that I could use as well.

**Comment by shabbirkagalwala** [comment] 2017-07-18 22:03
@vfarcic  I think I figured it out, the redirects work using redirectWhenHttpProto=true but now the issue is it only redirects if the service domain is used for example http://foo.bar -> https://foo.bar but if a path is added for example http://foo.bar/a/b it fails to redirect. I tried using service path but it didn't work.
Any suggestions?

As requested I will post the stack in a couple of minutes or maybe early tomorrow. Again thank you very much I really appreciate all your help, I owe you a lots of cups of coffee.

**Comment by vfarcic** [comment] 2017-07-19 07:28
Thanks for the info. I'll try it myself using domain and path. I don't think that scenario is covered in tests so there might be a glitch no one noticed. I'll do my best to go through it tonight.

**Comment by vfarcic** [comment] 2017-07-19 22:22
Can you send me proxy config (it's `/cfg/haproxy.cfg` inside the container), the stack, and an example request? That would help me replicate it much faster.

**Comment by shabbirkagalwala** [comment] 2017-07-21 18:08
@vfarcic I figured it out and I am sorry about the trouble as well, so the issue was we were using tcp/ssl protocols on the elb instead of http/https and that caused dfp not to redirect. Thank you so much for the help! You can close this ticket.

**Closed** 2017-07-22 09:58 UTC

**Comment by sunnykamboj47** [comment] 2019-11-01 06:05
> @vfarcic I think I figured it out, the redirects work using redirectWhenHttpProto=true but now the issue is it only redirects if the service domain is used for example http://foo.bar -> https://foo.bar but if a path is added for example http://foo.bar/a/b it fails to redirect. I tried using service path but it didn't work.
> Any suggestions?
> 
> As requested I will post the stack in a couple of minutes or maybe early tomorrow. Again thank you very much I really appreciate all your help, I owe you a lots of cups of coffee.


you also have to redirect the containers service to the http to https
for example if there tomcat is running then you have to redirect also tomcat  docker service also
